/-
Copyright (c) 2026 PolyFun Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Quang Dao
-/

module

public import PolyFun.PFunctor.Basic

/-!
# Displays over polynomial functors

A `PFunctor.Display P` is a polynomial family over a fixed polynomial functor `P`.
For every base position `a : P.A`, it provides a type of displayed positions; for
every displayed position and base direction `b : P.B a`, it provides a type of
displayed directions above `b`.

Displays are local, one-step objects. They should be distinguished from the
free-tree constructions in `PFunctor.FreeM.Displayed`:

* `PFunctor.Display P` refines one position and its directions in `P`;
* `FreeM.Displayed.Algebra P α` is an arbitrary higher-order recipe for assembling
  a fiber from the already-assembled fibers of the children of a free `P`-tree;
* `FreeM.Displayed D t` evaluates such a recipe over a concrete tree `t`;
* `FreeM.Displayed.Over E t d` adds a second fiber over existing displayed data
  `d : FreeM.Displayed D t`.

The node operator generated by a display has the polynomial form

```text
X ↦ Σ c, ∀ b, direction a c b → X b.
```

An arbitrary `FreeM.Displayed.Algebra` need not have this form: it may use child
fibers negatively, non-functorially, or by another higher-order operation. The
polynomial form is precisely what supports the indexed-polynomial comparison
and substitution through `FreeM` developed in the sibling display modules.

The fields and object action are `Type`-valued, matching polynomial functors,
indexed polynomial functors, and the `Set`-valued definition in Aberlé's
compositional-verification development. `Display.ofPredicates` embeds
`Prop`-valued contracts with `PLift`.
-/

@[expose] public section

universe uA uB uC uD uE uF uG uI uA₁ uA₂ uC₁ uC₂ uD₁ uD₂

namespace PFunctor

-- As for `PFunctor`, the position and direction universes are intentionally
-- independent.  This keeps `Display.total` directions and the child universe
-- of `Display.incidence` small when only displayed positions are large.
set_option linter.checkUnivs false in
/-- A polynomial display over a fixed polynomial functor `P`.

`position a` is the fiber over a base position `a`. After choosing
`c : position a`, `direction a c b` is the fiber over a base direction
`b : P.B a`. -/
@[ext]
structure Display (P : PFunctor.{uA, uB}) where
  /-- Displayed positions above each base position. -/
  position : P.A → Type uC
  /-- Displayed directions above each base direction. -/
  direction : (a : P.A) → position a → P.B a → Type uD

namespace Display

variable {P : PFunctor.{uA, uB}}

/-- Apply a display to a family `F` over a base object `E`, at one element of
the polynomial extension `P.Obj E`.

The displayed position is paired with one recursive child for every displayed
direction above every base direction. -/
def Obj (S : Display.{uA, uB, uC, uD} P) {E : Type uE}
    (F : E → Type uF) (x : P.Obj E) :=
  Sigma fun c : S.position x.1 =>
    (b : P.B x.1) → S.direction x.1 c b → F (x.2 b)

@[simp]
theorem obj_mk (S : Display.{uA, uB, uC, uD} P) {E : Type uE}
    (F : E → Type uF) (a : P.A) (next : P.B a → E) :
    S.Obj F ⟨a, next⟩ =
      Sigma fun c : S.position a =>
        (b : P.B a) → S.direction a c b → F (next b) :=
  rfl

namespace Obj

variable {S : Display.{uA, uB, uC, uD} P}
variable {E : Type uE} {F : E → Type uF} {G : E → Type uG}

/-- Map a display fiber pointwise along a map of the leaf family. -/
def map (f : (e : E) → F e → G e) (x : P.Obj E) :
    S.Obj F x → S.Obj G x
  | ⟨c, children⟩ => ⟨c, fun b d => f (x.2 b) (children b d)⟩

@[simp]
theorem map_apply (f : (e : E) → F e → G e) (x : P.Obj E)
    (c : S.position x.1)
    (children : (b : P.B x.1) → S.direction x.1 c b → F (x.2 b)) :
    map f x ⟨c, children⟩ =
      ⟨c, fun b d => f (x.2 b) (children b d)⟩ :=
  rfl

@[simp]
theorem map_id (x : P.Obj E) (d : S.Obj F x) :
    map (fun _ y => y) x d = d := by
  cases d with
  | mk c children =>
      congr

theorem map_comp {H : E → Type uI}
    (g : (e : E) → G e → H e) (f : (e : E) → F e → G e)
    (x : P.Obj E) (d : S.Obj F x) :
    map g x (map f x d) = map (fun e y => g e (f e y)) x d := by
  cases d with
  | mk c children =>
      congr

end Obj

/-! ## Predicate-valued contracts -/

/-- Embed predicate-valued position and direction contracts as a polynomial
display. `PLift` keeps `Display` genuinely `Type`-valued while retaining direct
support for ordinary propositions. -/
def ofPredicates
    (pre : P.A → Prop)
    (post : (a : P.A) → pre a → P.B a → Prop) :
    Display.{uA, uB, 0, 0} P where
  position a := PLift (pre a)
  direction a c b := PLift (post a c.down b)

@[simp]
theorem ofPredicates_position
    (pre : P.A → Prop)
    (post : (a : P.A) → pre a → P.B a → Prop) (a : P.A) :
    (ofPredicates pre post).position a = PLift (pre a) :=
  rfl

@[simp]
theorem ofPredicates_direction
    (pre : P.A → Prop)
    (post : (a : P.A) → pre a → P.B a → Prop)
    (a : P.A) (c : (ofPredicates pre post).position a) (b : P.B a) :
    (ofPredicates pre post).direction a c b = PLift (post a c.down b) :=
  rfl

/-! ## Coproducts -/

/-- The display over an indexed coproduct obtained from displays over each
summand. -/
def sigma {I : Type uI} {Ps : I → PFunctor.{uA, uB}}
    (S : (i : I) → Display.{uA, uB, uC, uD} (Ps i)) :
    Display.{max uA uI, uB, uC, uD} (PFunctor.sigma Ps) where
  position ia := S ia.1 |>.position ia.2
  direction ia c b := S ia.1 |>.direction ia.2 c b

@[simp]
theorem sigma_position {I : Type uI} {Ps : I → PFunctor.{uA, uB}}
    (S : (i : I) → Display.{uA, uB, uC, uD} (Ps i))
    (i : I) (a : (Ps i).A) :
    (sigma S).position ⟨i, a⟩ = (S i).position a :=
  rfl

@[simp]
theorem sigma_direction {I : Type uI} {Ps : I → PFunctor.{uA, uB}}
    (S : (i : I) → Display.{uA, uB, uC, uD} (Ps i))
    (i : I) (a : (Ps i).A) (c : (S i).position a) (b : (Ps i).B a) :
    (sigma S).direction ⟨i, a⟩ c b = (S i).direction a c b :=
  rfl

/-- Binary coproduct of polynomial displays. -/
def sum {Q : PFunctor.{uA₂, uB}}
    (S : Display.{uA, uB, uC₁, uD₁} P)
    (T : Display.{uA₂, uB, uC₂, uD₂} Q) :
    Display.{max uA uA₂, uB, max uC₁ uC₂, max uD₁ uD₂} (P + Q) where
  position
    | .inl a => ULift (S.position a)
    | .inr a => ULift (T.position a)
  direction a c b := match a with
    | .inl a => ULift (S.direction a c.down b)
    | .inr a => ULift (T.direction a c.down b)

@[simp]
theorem sum_position_inl {Q : PFunctor.{uA₂, uB}}
    (S : Display.{uA, uB, uC₁, uD₁} P)
    (T : Display.{uA₂, uB, uC₂, uD₂} Q) (a : P.A) :
    (sum S T).position (.inl a) = ULift (S.position a) :=
  rfl

@[simp]
theorem sum_position_inr {Q : PFunctor.{uA₂, uB}}
    (S : Display.{uA, uB, uC₁, uD₁} P)
    (T : Display.{uA₂, uB, uC₂, uD₂} Q) (a : Q.A) :
    (sum S T).position (.inr a) = ULift (T.position a) :=
  rfl

@[simp]
theorem sum_direction_inl {Q : PFunctor.{uA₂, uB}}
    (S : Display.{uA, uB, uC₁, uD₁} P)
    (T : Display.{uA₂, uB, uC₂, uD₂} Q)
    (a : P.A) (c : (sum S T).position (.inl a)) (b : P.B a) :
    (sum S T).direction (.inl a) c b = ULift (S.direction a c.down b) :=
  rfl

@[simp]
theorem sum_direction_inr {Q : PFunctor.{uA₂, uB}}
    (S : Display.{uA, uB, uC₁, uD₁} P)
    (T : Display.{uA₂, uB, uC₂, uD₂} Q)
    (a : Q.A) (c : (sum S T).position (.inr a)) (b : Q.B a) :
    (sum S T).direction (.inr a) c b = ULift (T.direction a c.down b) :=
  rfl

/-- The unique display over the zero polynomial. -/
def zero : Display.{uA, uB, uC, uD} (0 : PFunctor.{uA, uB}) where
  position := PEmpty.elim
  direction a := PEmpty.elim a

end Display
end PFunctor
