/-
Copyright (c) 2026 PolyFun Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Quang Dao
-/

module

public import PolyFun.PFunctor.Display.Basic
public import PolyFun.PFunctor.Free.Displayed

/-!
# Polynomial displays over free trees

This file is the precise bridge between `PFunctor.Display` and the older
`FreeM.Displayed` API. A display determines a particular displayed-family
shape at every node:

```text
X ↦ Σ c : S.position a, ∀ b, S.direction a c b → X b.
```

Thus the relationship is generation, not identification:

* `PFunctor.Display S` is one-step polynomial data over the operations of `P`;
* `S.toDisplayedShape F` embeds that data into the generic higher-order
  `FreeM.Displayed.Shape`, with `F` specifying the leaf fibers;
* `FreeM.Displayed (S.toDisplayedShape F) t` is the recursively evaluated
  fiber over a particular free tree `t`;
* `FreeM.Displayed.Over` remains a separate, second displayed layer over an
  inhabitant of any evaluated shape. It is not replaced by `Display`.

Every display-generated shape is polynomial and consequently admits the
dependent substitution operation below. Generic `FreeM.Displayed.Shape`s do
not: their `node` field can inspect child sorts negatively or otherwise
non-functorially. This is the extra theory supplied by `Display`, rather than
a duplicate spelling of the existing displayed-family definitions.
-/

@[expose] public section

universe uA uB uC uD uE uE' uF uG

namespace PFunctor
namespace Display

variable {P : PFunctor.{uA, uB}}

/-- Embed a one-step polynomial display into the generic displayed-family
shape over free `P`-trees, using `F` for the leaf fibers.

`ULift` places the leaf fibers in the common universe required by
`FreeM.Displayed.Shape`; `Display` itself keeps its position, direction, and
leaf universes independent. -/
def toDisplayedShape (S : Display.{uA, uB, uC, uD} P)
    {E : Type uE} (F : E → Type uF) : FreeM.Displayed.Shape P E where
  leaf x := ULift.{max uC uB uD} (F x)
  node a child :=
    Σ c : S.position a,
      (b : P.B a) → S.direction a c b → child b

@[simp]
theorem toDisplayedShape_leaf (S : Display.{uA, uB, uC, uD} P)
    {E : Type uE} (F : E → Type uF) (x : E) :
    (S.toDisplayedShape F).leaf x = ULift.{max uC uB uD} (F x) :=
  rfl

@[simp]
theorem toDisplayedShape_node (S : Display.{uA, uB, uC, uD} P)
    {E : Type uE} (F : E → Type uF) (a : P.A)
    (child : P.B a → Type (max uC uB uD uF)) :
    (S.toDisplayedShape F).node a child =
      (Σ c : S.position a,
        (b : P.B a) → S.direction a c b → child b) :=
  rfl

/-- The generated node operation is exactly `Display.Obj`, after lifting the
leaf family into the common universe required by `Displayed.Shape`. -/
theorem toDisplayedShape_node_eq_obj
    (S : Display.{uA, uB, uC, uD} P)
    {E : Type uE} (F : E → Type uF) (a : P.A) (next : P.B a → E) :
    (S.toDisplayedShape F).node a
        (fun b => ULift.{max uC uB uD} (F (next b))) =
      S.Obj (fun e => ULift.{max uC uB uD} (F e)) ⟨a, next⟩ :=
  rfl

/-- Introduce an unlifted leaf value into the displayed fiber generated by a
display. This is the public constructor that hides the universe lift used by
`toDisplayedShape`. -/
def leaf (S : Display.{uA, uB, uC, uD} P)
    {E : Type uE} (F : E → Type uF) (x : E) (d : F x) :
    FreeM.Displayed (S.toDisplayedShape F) (.pure x) :=
  ULift.up d

@[simp]
theorem leaf_down (S : Display.{uA, uB, uC, uD} P)
    {E : Type uE} (F : E → Type uF) (x : E) (d : F x) :
    (S.leaf F x d).down = d :=
  rfl

/-- Dependent substitution for a display-generated family over a free tree.

At a leaf, `dg` supplies displayed data over the substituted tree. The
universe lift used by `toDisplayedShape` is removed before calling it. At a node,
the displayed position is retained and substitution proceeds recursively in
each displayed direction. -/
def bind (S : Display.{uA, uB, uC, uD} P)
    {E : Type uE} {F : E → Type uF}
    {E' : Type uE'} {G : E' → Type uG}
    (t : FreeM P E)
    (d : FreeM.Displayed (S.toDisplayedShape F) t)
    (g : E → FreeM P E')
    (dg : (x : E) → F x → FreeM.Displayed (S.toDisplayedShape G) (g x)) :
    FreeM.Displayed (S.toDisplayedShape G) (t.bind g) :=
  match t, d with
  | .pure x, d => dg x d.down
  | .liftBind _ rest, ⟨c, children⟩ =>
      ⟨c, fun b e => S.bind (rest b) (children b e) g dg⟩

@[simp]
theorem bind_pure (S : Display.{uA, uB, uC, uD} P)
    {E : Type uE} {F : E → Type uF}
    {E' : Type uE'} {G : E' → Type uG}
    (x : E) (d : ULift.{max uC uB uD} (F x)) (g : E → FreeM P E')
    (dg : (x : E) → F x → FreeM.Displayed (S.toDisplayedShape G) (g x)) :
    S.bind (pure x) d g dg = dg x d.down :=
  rfl

@[simp]
theorem bind_liftBind (S : Display.{uA, uB, uC, uD} P)
    {E : Type uE} {F : E → Type uF}
    {E' : Type uE'} {G : E' → Type uG}
    (a : P.A) (rest : P.B a → FreeM P E)
    (c : S.position a)
    (children : (b : P.B a) → S.direction a c b →
      FreeM.Displayed (S.toDisplayedShape F) (rest b))
    (g : E → FreeM P E')
    (dg : (x : E) → F x → FreeM.Displayed (S.toDisplayedShape G) (g x)) :
    S.bind ((FreeM.lift a).bind rest) ⟨c, children⟩ g dg =
      ⟨c, fun b e => S.bind (rest b) (children b e) g dg⟩ :=
  rfl

/-! ## Transport -/

/-- Transport display-generated data along equality of its base free trees. -/
def transport (S : Display.{uA, uB, uC, uD} P)
    {E : Type uE} (F : E → Type uF) {t t' : FreeM P E}
    (h : t = t') :
    FreeM.Displayed (S.toDisplayedShape F) t →
      FreeM.Displayed (S.toDisplayedShape F) t' :=
  h ▸ id

@[simp]
theorem transport_rfl (S : Display.{uA, uB, uC, uD} P)
    {E : Type uE} (F : E → Type uF) {t : FreeM P E}
    (d : FreeM.Displayed (S.toDisplayedShape F) t) :
    S.transport F rfl d = d :=
  rfl

end Display
end PFunctor
