/-
Copyright (c) 2026 PolyFun Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Quang Dao
-/

module

public import PolyFun.PFunctor.Display.Basic
public import PolyFun.PFunctor.Free.Displayed

/-!
# Polynomial displays over free trees

This file is the precise bridge between `PFunctor.Display` and the older
`FreeM.Displayed` API. A display determines a particular displayed
algebra at every node:

```text
X ↦ Σ c : S.position a, ∀ b, S.direction a c b → X b.
```

Thus the relationship is generation, not identification:

* `PFunctor.Display S` is one-step polynomial data over the operations of `P`;
* `S.toDisplayedAlgebra F` embeds that data into the generic higher-order
  `FreeM.Displayed.Algebra`, with `F` specifying the leaf fibers;
* `FreeM.Displayed (S.toDisplayedAlgebra F) t` is the recursively evaluated
  fiber over a particular free tree `t`;
* `FreeM.Displayed.Over` remains a separate, second displayed layer over an
  inhabitant of any evaluated displayed algebra. It is not replaced by `Display`.

Every display-generated algebra is polynomial and consequently admits the
dependent substitution operation below. Generic `FreeM.Displayed.Algebra`s do
not: their `node` field can inspect child sorts negatively or otherwise
non-functorially. This is the extra theory supplied by `Display`, rather than
a duplicate spelling of the existing displayed-family definitions.
-/

@[expose] public section

universe uA uB uC uD uE uE' uE'' uF uG uH

namespace PFunctor
namespace Display

variable {P : PFunctor.{uA, uB}}

/-- Embed a one-step polynomial display into the generic displayed algebra over
free `P`-trees, using `F` for the leaf fibers.

`ULift` places the leaf fibers in the common universe required by
`FreeM.Displayed.Algebra`; `Display` itself keeps its position, direction, and
leaf universes independent. -/
def toDisplayedAlgebra (S : Display.{uA, uB, uC, uD} P)
    {E : Type uE} (F : E → Type uF) : FreeM.Displayed.Algebra P E where
  leaf x := ULift.{max uC uB uD} (F x)
  node a child :=
    Σ c : S.position a,
      (b : P.B a) → S.direction a c b → child b

@[simp]
theorem toDisplayedAlgebra_leaf (S : Display.{uA, uB, uC, uD} P)
    {E : Type uE} (F : E → Type uF) (x : E) :
    (S.toDisplayedAlgebra F).leaf x = ULift.{max uC uB uD} (F x) :=
  rfl

@[simp]
theorem toDisplayedAlgebra_node (S : Display.{uA, uB, uC, uD} P)
    {E : Type uE} (F : E → Type uF) (a : P.A)
    (child : P.B a → Type (max uC uB uD uF)) :
    (S.toDisplayedAlgebra F).node a child =
      (Σ c : S.position a,
        (b : P.B a) → S.direction a c b → child b) :=
  rfl

/-- The generated node operation is exactly `Display.Obj`, after lifting the
leaf family into the common universe required by `Displayed.Algebra`. -/
theorem toDisplayedAlgebra_node_eq_obj
    (S : Display.{uA, uB, uC, uD} P)
    {E : Type uE} (F : E → Type uF) (a : P.A) (next : P.B a → E) :
    (S.toDisplayedAlgebra F).node a
        (fun b => ULift.{max uC uB uD} (F (next b))) =
      S.Obj (fun e => ULift.{max uC uB uD} (F e)) ⟨a, next⟩ :=
  rfl

/-- Introduce an unlifted leaf value into the displayed fiber generated by a
display. This is the public constructor that hides the universe lift used by
`toDisplayedAlgebra`. -/
def leaf (S : Display.{uA, uB, uC, uD} P)
    {E : Type uE} (F : E → Type uF) (x : E) (d : F x) :
    FreeM.Displayed (S.toDisplayedAlgebra F) (.pure x) :=
  ULift.up d

@[simp]
theorem leaf_down (S : Display.{uA, uB, uC, uD} P)
    {E : Type uE} (F : E → Type uF) (x : E) (d : F x) :
    (S.leaf F x d).down = d :=
  rfl

/-- Dependent substitution for a display-generated family over a free tree.

At a leaf, `dg` supplies displayed data over the substituted tree. The
universe lift used by `toDisplayedAlgebra` is removed before calling it. At a node,
the displayed position is retained and substitution proceeds recursively in
each displayed direction. -/
def bind (S : Display.{uA, uB, uC, uD} P)
    {E : Type uE} {F : E → Type uF}
    {E' : Type uE'} {G : E' → Type uG}
    (t : FreeM P E)
    (d : FreeM.Displayed (S.toDisplayedAlgebra F) t)
    (g : E → FreeM P E')
    (dg : (x : E) → F x → FreeM.Displayed (S.toDisplayedAlgebra G) (g x)) :
    FreeM.Displayed (S.toDisplayedAlgebra G) (t.bind g) :=
  match t, d with
  | .pure x, d => dg x d.down
  | .liftBind _ rest, ⟨c, children⟩ =>
      ⟨c, fun b e => S.bind (rest b) (children b e) g dg⟩

@[simp]
theorem bind_pure (S : Display.{uA, uB, uC, uD} P)
    {E : Type uE} {F : E → Type uF}
    {E' : Type uE'} {G : E' → Type uG}
    (x : E) (d : ULift.{max uC uB uD} (F x)) (g : E → FreeM P E')
    (dg : (x : E) → F x → FreeM.Displayed (S.toDisplayedAlgebra G) (g x)) :
    S.bind (pure x) d g dg = dg x d.down :=
  rfl

@[simp]
theorem bind_liftBind (S : Display.{uA, uB, uC, uD} P)
    {E : Type uE} {F : E → Type uF}
    {E' : Type uE'} {G : E' → Type uG}
    (a : P.A) (rest : P.B a → FreeM P E)
    (c : S.position a)
    (children : (b : P.B a) → S.direction a c b →
      FreeM.Displayed (S.toDisplayedAlgebra F) (rest b))
    (g : E → FreeM P E')
    (dg : (x : E) → F x → FreeM.Displayed (S.toDisplayedAlgebra G) (g x)) :
    S.bind ((FreeM.lift a).bind rest) ⟨c, children⟩ g dg =
      ⟨c, fun b e => S.bind (rest b) (children b e) g dg⟩ :=
  rfl

/-! ## Transport -/

/-- Transport display-generated data along equality of its base free trees. -/
def transport (S : Display.{uA, uB, uC, uD} P)
    {E : Type uE} (F : E → Type uF) {t t' : FreeM P E}
    (h : t = t') :
    FreeM.Displayed (S.toDisplayedAlgebra F) t →
      FreeM.Displayed (S.toDisplayedAlgebra F) t' :=
  h ▸ id

@[simp]
theorem transport_rfl (S : Display.{uA, uB, uC, uD} P)
    {E : Type uE} (F : E → Type uF) {t : FreeM P E}
    (d : FreeM.Displayed (S.toDisplayedAlgebra F) t) :
    S.transport F rfl d = d :=
  rfl

/-- Transport is independent of the proof chosen for a fixed base-tree
equality.  This is the normalization lemma for replacing an opaque library
proof by a structurally recursive proof of the same equality. -/
theorem transport_proof_irrel (S : Display.{uA, uB, uC, uD} P)
    {E : Type uE} (F : E → Type uF) {t t' : FreeM P E}
    (h h' : t = t') (d : FreeM.Displayed (S.toDisplayedAlgebra F) t) :
    S.transport F h d = S.transport F h' d := by
  cases h
  rfl

/-- Successive transports compose.  This is the public normalization lemma
for proofs whose base-tree indices are changed by more than one free-monad
law. -/
theorem transport_trans (S : Display.{uA, uB, uC, uD} P)
    {E : Type uE} (F : E → Type uF) {t t' t'' : FreeM P E}
    (h : t = t') (h' : t' = t'')
    (d : FreeM.Displayed (S.toDisplayedAlgebra F) t) :
    S.transport F h' (S.transport F h d) = S.transport F (h.trans h') d := by
  cases h
  cases h'
  rfl

/-- Transporting forward and then backward along the same base-tree equality
recovers the original displayed data. -/
theorem transport_symm (S : Display.{uA, uB, uC, uD} P)
    {E : Type uE} (F : E → Type uF) {t t' : FreeM P E}
    (h : t = t') (d : FreeM.Displayed (S.toDisplayedAlgebra F) t) :
    S.transport F h.symm (S.transport F h d) = d := by
  cases h
  rfl

/-- Transport along equality of the substitution function acts pointwise on
the displayed data supplied at leaves. -/
theorem transport_bind (S : Display.{uA, uB, uC, uD} P)
    {E : Type uE} {F : E → Type uF}
    {E' : Type uE'} {G : E' → Type uG}
    (t : FreeM P E) (d : FreeM.Displayed (S.toDisplayedAlgebra F) t)
    {g g' : E → FreeM P E'} (h : g = g')
    (dg : (x : E) → F x → FreeM.Displayed (S.toDisplayedAlgebra G) (g x)) :
    S.transport G (congrArg (t.bind ·) h) (S.bind t d g dg) =
      S.bind t d g'
        (fun x dx => S.transport G (congrFun h x) (dg x dx)) := by
  cases h
  rfl

/-- Transporting a displayed node along equality of its continuation family
acts pointwise on the displayed children. -/
theorem transport_liftBind (S : Display.{uA, uB, uC, uD} P)
    {E : Type uE} (F : E → Type uF) (a : P.A)
    {rest rest' : P.B a → FreeM P E} (h : rest = rest')
    (c : S.position a)
    (children : (b : P.B a) → S.direction a c b →
      FreeM.Displayed (S.toDisplayedAlgebra F) (rest b)) :
    S.transport F (congrArg (FreeM.liftBind a) h) ⟨c, children⟩ =
      ⟨c, fun b e => S.transport F (congrFun h b) (children b e)⟩ := by
  cases h
  rfl

/-! ## Displayed monad laws -/

private theorem bindPureEq {E : Type uE} :
    (t : FreeM P E) → t.bind FreeM.pure = t
  | .pure _ => rfl
  | .liftBind a rest =>
      congrArg (FreeM.liftBind a) (funext fun b => bindPureEq (rest b))

private theorem bindAssocEq {E : Type uE} {E' : Type uE'} {E'' : Type uE''}
    (g : E → FreeM P E') (h : E' → FreeM P E'') :
    (t : FreeM P E) → (t.bind g).bind h = t.bind (fun x => (g x).bind h)
  | .pure _ => rfl
  | .liftBind a rest =>
      congrArg (FreeM.liftBind a) (funext fun b => bindAssocEq g h (rest b))

/-- Binding every leaf to the displayed leaf constructor is the right unit,
after transporting along the corresponding base-tree right-unit equality. -/
theorem bind_leaf (S : Display.{uA, uB, uC, uD} P)
    {E : Type uE} {F : E → Type uF}
    (t : FreeM P E) (d : FreeM.Displayed (S.toDisplayedAlgebra F) t) :
    S.transport F (FreeM.bind_pure t)
        (S.bind t d FreeM.pure fun x dx => S.leaf F x dx) = d := by
  induction t with
  | pure x =>
      cases d
      rfl
  | lift_bind a rest ih =>
      rcases d with ⟨c, children⟩
      simp only [FreeM.pure_bind] at children
      simp only [bind_liftBind]
      rw [S.transport_proof_irrel F
        (FreeM.bind_pure ((FreeM.lift a).bind rest))
        (bindPureEq ((FreeM.lift a).bind rest))]
      change S.transport F (bindPureEq (FreeM.liftBind a rest))
          ⟨c, fun b e =>
            S.bind (rest b) (children b e) FreeM.pure fun x dx =>
              S.leaf F x dx⟩ = ⟨c, children⟩
      have htransport :
          S.transport F (bindPureEq (FreeM.liftBind a rest))
              ⟨c, fun b e =>
                S.bind (rest b) (children b e) FreeM.pure fun x dx =>
                  S.leaf F x dx⟩ =
            ⟨c, fun b e =>
              S.transport F (bindPureEq (rest b))
                (S.bind (rest b) (children b e) FreeM.pure fun x dx =>
                  S.leaf F x dx)⟩ := by
        convert S.transport_liftBind F a
          (funext fun b => bindPureEq (rest b)) c
          (fun b e =>
            S.bind (rest b) (children b e) FreeM.pure fun x dx =>
              S.leaf F x dx) using 1
        all_goals simp [FreeM.liftBind_eq]
        all_goals congr
      rw [htransport]
      congr
      funext b e
      rw [S.transport_proof_irrel F (bindPureEq (rest b))
        (FreeM.bind_pure (rest b))]
      exact ih b (children b e)

/-- Displayed substitution is associative, with the left-associated result
transported along `FreeM.bind_assoc` to the right-associated base tree. -/
theorem bind_assoc (S : Display.{uA, uB, uC, uD} P)
    {E : Type uE} {F : E → Type uF}
    {E' : Type uE'} {G : E' → Type uG}
    {E'' : Type uE''} {H : E'' → Type uH}
    (t : FreeM P E) (d : FreeM.Displayed (S.toDisplayedAlgebra F) t)
    (g : E → FreeM P E')
    (dg : (x : E) → F x → FreeM.Displayed (S.toDisplayedAlgebra G) (g x))
    (h : E' → FreeM P E'')
    (dh : (x : E') → G x → FreeM.Displayed (S.toDisplayedAlgebra H) (h x)) :
    S.transport H (FreeM.bind_assoc t g h)
        (S.bind (t.bind g) (S.bind t d g dg) h dh) =
      S.bind t d (fun x => (g x).bind h)
        (fun x dx => S.bind (g x) (dg x dx) h dh) := by
  induction t with
  | pure x =>
      cases d
      rfl
  | lift_bind a rest ih =>
      rcases d with ⟨c, children⟩
      simp only [FreeM.pure_bind] at children
      simp only [bind_liftBind]
      rw [S.transport_proof_irrel H
        (FreeM.bind_assoc ((FreeM.lift a).bind rest) g h)
        (bindAssocEq g h ((FreeM.lift a).bind rest))]
      change S.transport H (bindAssocEq g h (FreeM.liftBind a rest))
          ⟨c, fun b e =>
            S.bind ((rest b).bind g) (S.bind (rest b) (children b e) g dg) h dh⟩ =
        ⟨c, fun b e =>
          S.bind (rest b) (children b e) (fun x => (g x).bind h)
            fun x dx => S.bind (g x) (dg x dx) h dh⟩
      have htransport :
          S.transport H (bindAssocEq g h (FreeM.liftBind a rest))
              ⟨c, fun b e =>
                S.bind ((rest b).bind g)
                  (S.bind (rest b) (children b e) g dg) h dh⟩ =
            ⟨c, fun b e =>
              S.transport H (bindAssocEq g h (rest b))
                (S.bind ((rest b).bind g)
                  (S.bind (rest b) (children b e) g dg) h dh)⟩ := by
        convert S.transport_liftBind H a
          (funext fun b => bindAssocEq g h (rest b)) c
          (fun b e =>
            S.bind ((rest b).bind g)
              (S.bind (rest b) (children b e) g dg) h dh) using 1
        all_goals simp [FreeM.liftBind_eq]
        all_goals congr
      rw [htransport]
      congr
      funext b e
      rw [S.transport_proof_irrel H (bindAssocEq g h (rest b))
        (FreeM.bind_assoc (rest b) g h)]
      exact ih b (children b e)

/-- Reverse orientation of displayed substitution associativity. -/
theorem bind_assoc_symm (S : Display.{uA, uB, uC, uD} P)
    {E : Type uE} {F : E → Type uF}
    {E' : Type uE'} {G : E' → Type uG}
    {E'' : Type uE''} {H : E'' → Type uH}
    (t : FreeM P E) (d : FreeM.Displayed (S.toDisplayedAlgebra F) t)
    (g : E → FreeM P E')
    (dg : (x : E) → F x → FreeM.Displayed (S.toDisplayedAlgebra G) (g x))
    (h : E' → FreeM P E'')
    (dh : (x : E') → G x → FreeM.Displayed (S.toDisplayedAlgebra H) (h x)) :
    S.transport H (FreeM.bind_assoc t g h).symm
        (S.bind t d (fun x => (g x).bind h)
          (fun x dx => S.bind (g x) (dg x dx) h dh)) =
      S.bind (t.bind g) (S.bind t d g dg) h dh := by
  rw [← S.bind_assoc t d g dg h dh]
  exact S.transport_symm H (FreeM.bind_assoc t g h)
    (S.bind (t.bind g) (S.bind t d g dg) h dh)

end Display
end PFunctor
