/-
Copyright (c) 2026 PolyFun Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Quang Dao
-/

module

public import PolyFun.PFunctor.Display.Basic
public import PolyFun.IPFunctor.Basic

/-!
# Indexed-polynomial views of displays

`IPFunctor I J` is a general indexed polynomial between two fixed family
categories. A display over `P` is more specialized: it refines the positions
and directions of one fixed polynomial and thereby generates indexed
polynomials uniformly as the base carrier varies.

This file provides both useful views:

* `Display.incidence S : IPFunctor P.Idx P.A` records the displayed incidence
  relation above the positions and directions of `P`;
* `Display.action S E : IPFunctor E (P.Obj E)` substitutes each base
  continuation into that incidence relation.

The second view acts on a family `F : E → Type` by the same formula as
`Display.Obj`. The only representational difference is that `IPFunctor.Obj`
uses a function out of one sigma type of directions, while `Display.Obj` uses
its curried form. `Display.actionObjEquiv` packages the resulting equivalence.
-/

@[expose] public section

universe uA uB uC uD uE uF

namespace PFunctor
namespace Display

variable {P : PFunctor.{uA, uB}}

/-- The indexed polynomial recording the incidence of displayed directions
above the base directions of `P`. -/
def incidence (S : Display.{uA, uB, uC, uD} P) :
    IPFunctor P.Idx P.A where
  A a := S.position a
  B a c := Σ b, S.direction a c b
  src a _ bd := ⟨a, bd.1⟩

@[simp]
theorem incidence_src (S : Display.{uA, uB, uC, uD} P)
    (a : P.A) (c : S.position a) (b : P.B a)
    (d : S.direction a c b) :
    S.incidence.src a c ⟨b, d⟩ = ⟨a, b⟩ :=
  rfl

/-- The indexed polynomial generated by a display after substituting a base
continuation `P.B a → E` into its direction incidence. -/
def action (S : Display.{uA, uB, uC, uD} P) (E : Type uE) :
    IPFunctor E (P.Obj E) where
  A x := S.position x.1
  B x c := Σ b, S.direction x.1 c b
  src x _ bd := x.2 bd.1

@[simp]
theorem action_src (S : Display.{uA, uB, uC, uD} P)
    {E : Type uE} (a : P.A) (next : P.B a → E)
    (c : S.position a) (b : P.B a) (d : S.direction a c b) :
    (S.action E).src ⟨a, next⟩ c ⟨b, d⟩ = next b :=
  rfl

/-- Applying the indexed polynomial generated by a display is equivalent to
the display's curried object action. -/
def actionObjEquiv (S : Display.{uA, uB, uC, uD} P)
    {E : Type uE} (F : E → Type uF) (x : P.Obj E) :
    (S.action E).Obj F x ≃ S.Obj F x where
  toFun d := ⟨d.1, fun b e => d.2 ⟨b, e⟩⟩
  invFun d := ⟨d.1, fun be => d.2 be.1 be.2⟩
  left_inv d := by
    cases d with
    | mk c children =>
        congr
  right_inv d := by
    cases d with
    | mk c children =>
        congr

@[simp]
theorem actionObjEquiv_apply (S : Display.{uA, uB, uC, uD} P)
    {E : Type uE} (F : E → Type uF) (x : P.Obj E)
    (d : (S.action E).Obj F x) :
    S.actionObjEquiv F x d = ⟨d.1, fun b e => d.2 ⟨b, e⟩⟩ :=
  rfl

@[simp]
theorem actionObjEquiv_symm_apply (S : Display.{uA, uB, uC, uD} P)
    {E : Type uE} (F : E → Type uF) (x : P.Obj E)
    (d : S.Obj F x) :
    (S.actionObjEquiv F x).symm d = ⟨d.1, fun be => d.2 be.1 be.2⟩ :=
  rfl

end Display
end PFunctor
