/-
Copyright (c) 2026 PolyFun Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Quang Dao
-/

module

public import PolyFun.IPFunctor.M
public import PolyFun.PFunctor.Display.Indexed

/-!
# Displayed M-types

For a display `S : PFunctor.Display P` and a fixed base behavior
`tree : PFunctor.M P`, `Display.M S tree` is the greatest displayed fixed
point over `tree`.  A displayed node chooses `S.position tree.head`; each pair
of a base direction and a displayed direction recursively lies over the
corresponding base child.

This is not `FreeM.Displayed`.  The latter is an inductive fiber over a finite
free tree generated by a higher-order displayed algebra.  `Display.M` is a
coinductive fiber over a possibly infinite ordinary M-tree, generated by the
one-step polynomial display itself.
-/

@[expose] public section

universe uA uB uC uD uX uY

namespace PFunctor
namespace Display

variable {P : PFunctor.{uA, uB}}

/-- The indexed polynomial whose indexed M-type is the coinductive display
fiber over an ordinary `P`-behavior tree. -/
def mStep (S : Display.{uA, uB, uC, uD} P) :
    IPFunctor.Endo (PFunctor.M P) where
  A tree := S.position (PFunctor.M.head tree)
  B tree displayedShape :=
    Σ direction : P.B (PFunctor.M.head tree),
      S.direction (PFunctor.M.head tree) displayedShape direction
  src tree _ direction := PFunctor.M.children tree direction.1

@[simp]
theorem mStep_src (S : Display.{uA, uB, uC, uD} P)
    (tree : PFunctor.M P) (displayedShape : S.position tree.head)
    (direction : P.B tree.head)
    (displayedDirection : S.direction tree.head displayedShape direction) :
    (mStep S).src tree displayedShape ⟨direction, displayedDirection⟩ =
      tree.children direction :=
  rfl

/-- The coinductive display fiber over a fixed ordinary M-tree. -/
abbrev M (S : Display.{uA, uB, uC, uD} P) (tree : PFunctor.M P) :=
  IPFunctor.IM (mStep S) tree

namespace M

variable {S : Display.{uA, uB, uC, uD} P} {tree : PFunctor.M P}

/-- Transport a displayed behavior along equality of its base behavior. -/
def transport {left right : PFunctor.M P} (h : left = right) :
    Display.M S left → Display.M S right :=
  h ▸ id

/-- Equality of base behaviors induces an equivalence of their displayed
fibers. -/
def transportEquiv {left right : PFunctor.M P} (h : left = right) :
    Display.M S left ≃ Display.M S right where
  toFun := transport h
  invFun := transport h.symm
  left_inv displayedTree := by
    cases h
    rfl
  right_inv displayedTree := by
    cases h
    rfl

@[simp]
theorem transportEquiv_apply {left right : PFunctor.M P}
    (h : left = right) (displayedTree : Display.M S left) :
    transportEquiv (S := S) h displayedTree = transport h displayedTree :=
  rfl

@[simp]
theorem transportEquiv_symm_apply {left right : PFunctor.M P}
    (h : left = right) (displayedTree : Display.M S right) :
    (transportEquiv (S := S) h).symm displayedTree =
      transport h.symm displayedTree :=
  rfl

@[simp]
theorem transport_rfl (displayedTree : Display.M S tree) :
    transport (S := S) rfl displayedTree = displayedTree :=
  rfl

theorem transport_proof_irrel {left right : PFunctor.M P}
    (h h' : left = right) (displayedTree : Display.M S left) :
    transport (S := S) h displayedTree = transport h' displayedTree := by
  cases h
  rfl

theorem transport_trans {first second third : PFunctor.M P}
    (h : first = second) (h' : second = third)
    (displayedTree : Display.M S first) :
    transport (S := S) h' (transport h displayedTree) =
      transport (h.trans h') displayedTree := by
  cases h
  cases h'
  rfl

theorem transport_injective {left right : PFunctor.M P}
    (h : left = right) : Function.Injective (transport (S := S) h) := by
  cases h
  exact Function.injective_id

/-- Transport changes only the indexed root certificate; the sigma-erased
coinductive tree is unchanged. -/
@[simp]
theorem toM_transport {left right : PFunctor.M P}
    (h : left = right) (displayedTree : Display.M S left) :
    (transport (S := S) h displayedTree).toM = displayedTree.toM := by
  cases h
  rfl

@[simp]
theorem transport_symm_transport {left right : PFunctor.M P}
    (h : left = right) (displayedTree : Display.M S left) :
    transport (S := S) h.symm (transport h displayedTree) = displayedTree :=
  (transportEquiv (S := S) h).left_inv displayedTree

theorem transport_transport_symm {left right : PFunctor.M P}
    (h : left = right) (displayedTree : Display.M S right) :
    transport (S := S) h (transport h.symm displayedTree) = displayedTree :=
  (transportEquiv (S := S) h).right_inv displayedTree

/-- The displayed position at the root. -/
def head (displayedTree : Display.M S tree) : S.position tree.head :=
  IPFunctor.IM.head displayedTree

/-- The displayed subtree selected by a base direction and a displayed
direction above it. -/
def child (displayedTree : Display.M S tree)
    (direction : P.B tree.head)
    (displayedDirection : S.direction tree.head displayedTree.head direction) :
    Display.M S (tree.children direction) :=
  IPFunctor.IM.child displayedTree ⟨direction, displayedDirection⟩

/-- Destructor of the displayed final coalgebra over a fixed base tree. -/
def dest (displayedTree : Display.M S tree) :
    S.Obj (Display.M S) (PFunctor.M.dest tree) :=
  ⟨displayedTree.head, displayedTree.child⟩

/-- Constructor of the displayed final coalgebra over a fixed base tree. -/
def mk (node : S.Obj (Display.M S) (PFunctor.M.dest tree)) :
    Display.M S tree :=
  IPFunctor.IM.mk
    ⟨node.1, fun direction => node.2 direction.1 direction.2⟩

@[simp]
theorem head_mk (node : S.Obj (Display.M S) (PFunctor.M.dest tree)) :
    (mk node).head = node.1 :=
  rfl

@[simp]
theorem dest_mk (node : S.Obj (Display.M S) (PFunctor.M.dest tree)) :
    dest (mk node) = node := by
  rcases node with ⟨displayedShape, children⟩
  rfl

@[simp]
theorem mk_dest (displayedTree : Display.M S tree) :
    mk (dest displayedTree) = displayedTree :=
  IPFunctor.IM.mk_dest displayedTree

/-- Equality of displayed M-trees follows from equality of their one-step
destructions. -/
theorem eq_of_dest_eq {left right : Display.M S tree}
    (h : dest left = dest right) : left = right := by
  rw [← mk_dest left, ← mk_dest right, h]

@[simp]
theorem dest_inj {left right : Display.M S tree} :
    dest left = dest right ↔ left = right :=
  ⟨eq_of_dest_eq, fun h => h ▸ rfl⟩

/-- Constructor/destructor equivalence for a displayed M-fiber. -/
def destEquiv : Display.M S tree ≃
    S.Obj (Display.M S) (PFunctor.M.dest tree) where
  toFun := dest
  invFun := mk
  left_inv := mk_dest
  right_inv := dest_mk

/-- The display object action and the indexed polynomial action defining
`Display.M` are the same one-step data, in curried and paired form. -/
def stepEquiv (X : PFunctor.M P → Type uX) (tree : PFunctor.M P) :
    (mStep S).Obj X tree ≃ S.Obj X (PFunctor.M.dest tree) where
  toFun node := ⟨node.1, fun direction displayedDirection =>
    node.2 ⟨direction, displayedDirection⟩⟩
  invFun node := ⟨node.1, fun direction =>
    node.2 direction.1 direction.2⟩
  left_inv node := by
    rcases node with ⟨displayedShape, children⟩
    congr
  right_inv node := by
    rcases node with ⟨displayedShape, children⟩
    congr

/-- The specialized displayed destructor is the curried view of the generic
indexed-M destructor. -/
theorem dest_eq_stepEquiv (displayedTree : Display.M S tree) :
    dest displayedTree =
      stepEquiv (S := S) (Display.M S) tree
        (IPFunctor.IM.dest displayedTree) :=
  rfl

/-- Corecursor for displayed M-types, expressed in the native curried
`Display.Obj` interface. -/
def corec (X : PFunctor.M P → Type uX)
    (step : (tree : PFunctor.M P) → X tree →
      S.Obj X (PFunctor.M.dest tree))
    (tree : PFunctor.M P) (state : X tree) : Display.M S tree :=
  IPFunctor.IM.corec
    (fun tree state => (stepEquiv (S := S) X tree).symm (step tree state))
    tree state

/-- The defining equation of displayed corecursion. -/
@[simp]
theorem dest_corec (X : PFunctor.M P → Type uX)
    (step : (tree : PFunctor.M P) → X tree →
      S.Obj X (PFunctor.M.dest tree))
    (tree : PFunctor.M P) (state : X tree) :
    dest (corec (S := S) X step tree state) =
      Display.Obj.map
        (fun nextTree nextState => corec (S := S) X step nextTree nextState)
        (PFunctor.M.dest tree) (step tree state) := by
  rcases hStep : step tree state with ⟨displayedShape, children⟩
  rw [dest_eq_stepEquiv]
  change stepEquiv (S := S) (Display.M S) tree
      (IPFunctor.IM.dest
        (IPFunctor.IM.corec
          (fun tree state =>
            (stepEquiv (S := S) X tree).symm (step tree state)) tree state)) = _
  rw [IPFunctor.IM.dest_corec]
  rw [hStep]
  rfl

/-- Displayed corecursion is the unique fiberwise map commuting with the
displayed destructors. -/
theorem corec_unique (X : PFunctor.M P → Type uX)
    (step : (tree : PFunctor.M P) → X tree →
      S.Obj X (PFunctor.M.dest tree))
    (f : (tree : PFunctor.M P) → X tree → Display.M S tree)
    (commute : ∀ tree state,
      dest (f tree state) =
        Display.Obj.map (fun nextTree nextState => f nextTree nextState)
          (PFunctor.M.dest tree) (step tree state)) :
    f = fun tree state => corec (S := S) X step tree state := by
  apply IPFunctor.IM.corec_unique
  intro tree state
  apply (stepEquiv (S := S) (Display.M S) tree).injective
  rw [← dest_eq_stepEquiv, commute]
  rcases hStep : step tree state with ⟨displayedShape, children⟩
  rfl

/-- Corecursing from the displayed destructor is the identity. -/
@[simp]
theorem corec_dest (displayedTree : Display.M S tree) :
    corec (S := S) (Display.M S) (fun _ next => dest next)
      tree displayedTree = displayedTree := by
  have h := corec_unique (S := S) (Display.M S)
    (fun _ next => dest next) (fun _ next => next) (by
      intro nextTree next
      exact (Display.Obj.map_id (S := S)
        (PFunctor.M.dest nextTree) next.dest).symm)
  exact congrFun (congrFun h tree) displayedTree |>.symm

/-! ## Bisimulation -/

/-- A cast-free bisimulation on displayed M-types.  Related displayed trees
choose one common displayed position and relate every corresponding child over
the same base and displayed directions. -/
def IsBisimulation
    (R : (tree : PFunctor.M P) →
      Display.M S tree → Display.M S tree → Prop) : Prop :=
  ∀ tree left right, R tree left right →
    ∃ displayedShape,
      ∃ leftChildren rightChildren :
        (direction : P.B tree.head) →
          S.direction tree.head displayedShape direction →
            Display.M S (tree.children direction),
      dest left = ⟨displayedShape, leftChildren⟩ ∧
      dest right = ⟨displayedShape, rightChildren⟩ ∧
      ∀ direction displayedDirection,
        R (tree.children direction)
          (leftChildren direction displayedDirection)
          (rightChildren direction displayedDirection)

/-- Displayed bisimulation implies equality without exposing the underlying
indexed-M representation. -/
theorem bisim
    (R : (tree : PFunctor.M P) →
      Display.M S tree → Display.M S tree → Prop)
    (hR : IsBisimulation (S := S) R)
    {tree : PFunctor.M P} {left right : Display.M S tree}
    (h : R tree left right) : left = right := by
  apply IPFunctor.IM.bisim R
  · intro current indexedLeft indexedRight hRelated
    rcases hR current indexedLeft indexedRight hRelated with
      ⟨displayedShape, leftChildren, rightChildren,
        hLeftDest, hRightDest, hChildren⟩
    refine
      ⟨displayedShape,
        (fun direction => leftChildren direction.1 direction.2),
        (fun direction => rightChildren direction.1 direction.2),
        ?_, ?_, ?_⟩
    · apply (stepEquiv (S := S) (Display.M S) current).injective
      rw [← dest_eq_stepEquiv, hLeftDest]
      rfl
    · apply (stepEquiv (S := S) (Display.M S) current).injective
      rw [← dest_eq_stepEquiv, hRightDest]
      rfl
    · intro direction
      exact hChildren direction.1 direction.2
  · exact h

/-- Two displayed corecursors are equal when a fiberwise relation on their
seed states matches one-step displayed shapes and all corresponding children.
This is the seed-level form of displayed coinduction. -/
theorem corec_eq_corec
    (X : PFunctor.M P → Type uX) (Y : PFunctor.M P → Type uY)
    (stepX : (tree : PFunctor.M P) → X tree →
      S.Obj X (PFunctor.M.dest tree))
    (stepY : (tree : PFunctor.M P) → Y tree →
      S.Obj Y (PFunctor.M.dest tree))
    (R : (tree : PFunctor.M P) → X tree → Y tree → Prop)
    (tree : PFunctor.M P) (x : X tree) (y : Y tree)
    (hR : R tree x y)
    (hStep : ∀ tree x y, R tree x y →
      ∃ displayedShape,
        ∃ childrenX : (direction : P.B tree.head) →
            S.direction tree.head displayedShape direction →
              X (tree.children direction),
        ∃ childrenY : (direction : P.B tree.head) →
            S.direction tree.head displayedShape direction →
              Y (tree.children direction),
        stepX tree x = ⟨displayedShape, childrenX⟩ ∧
        stepY tree y = ⟨displayedShape, childrenY⟩ ∧
        ∀ direction displayedDirection,
          R (tree.children direction)
            (childrenX direction displayedDirection)
            (childrenY direction displayedDirection)) :
    corec (S := S) X stepX tree x =
      corec (S := S) Y stepY tree y := by
  let relation := fun current left right =>
    ∃ x y, R current x y ∧
      left = corec (S := S) X stepX current x ∧
      right = corec (S := S) Y stepY current y
  apply bisim relation
  · intro current left right h
    rcases h with ⟨currentX, currentY, hRelated, rfl, rfl⟩
    rcases hStep current currentX currentY hRelated with
      ⟨displayedShape, childrenX, childrenY,
        hStepX, hStepY, hChildren⟩
    refine
      ⟨displayedShape,
        (fun direction displayedDirection =>
          corec (S := S) X stepX _
            (childrenX direction displayedDirection)),
        (fun direction displayedDirection =>
          corec (S := S) Y stepY _
            (childrenY direction displayedDirection)),
        ?_, ?_, ?_⟩
    · rw [dest_corec, hStepX]
      rfl
    · rw [dest_corec, hStepY]
      rfl
    · intro direction displayedDirection
      exact
        ⟨childrenX direction displayedDirection,
          childrenY direction displayedDirection,
          hChildren direction displayedDirection, rfl, rfl⟩
  · exact ⟨x, y, hR, rfl, rfl⟩

end M
end Display
end PFunctor
