/-
Copyright (c) 2026 PolyFun Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Devon Tuma
-/

module

import PolyFun.Control.Do.Spec
import PolyFun.Control.Monad.Algebra
import PolyFun.Control.Monad.Algebra.Relational
import PolyFun.Control.Monad.Algebra.Restrict
import PolyFun.Control.Monad.Algebra.WP
import PolyFun.Control.Monad.Free
import PolyFun.Control.Monad.Hom
import PolyFun.Control.Monad.Hom.Loops
import PolyFun.Control.Monad.Indexed
import PolyFun.Control.Monad.Support
import PolyFun.Control.Monad.Support.Indexed
import PolyFun.Control.Monad.Support.Instances
import PolyFun.Control.Monad.Support.WP
import PolyFun.Control.Trace
import PolyFun.ITree.Basic
import PolyFun.Interaction.Basic.Sampler
import PolyFun.Interaction.Basic.TypeTreeFintype
import PolyFun.Interaction.Concurrent.Fairness
import PolyFun.Interaction.Execution.ReactiveNetwork.Behavior
import PolyFun.Interaction.Execution.ReactiveNetwork.Budget
import PolyFun.Interaction.Execution.ReactiveNetwork.HandledAssembly
import PolyFun.Interaction.Execution.ReactiveNetwork.Serial
import PolyFun.Interaction.Execution.ReactiveNetwork.Transport
import PolyFun.Interaction.Execution.RequestNetwork
import PolyFun.Interaction.Execution.RequestNetwork.Serial
import PolyFun.Interaction.Execution.RequestNetwork.Transport
import PolyFun.Interaction.Interface
import PolyFun.Interaction.Multiparty.ObservationProfile
import PolyFun.Interaction.Open.Emulates
import PolyFun.Interaction.Open.EnvOpenProcess
import PolyFun.Interaction.Open.Notation
import PolyFun.Interaction.Open.OpenProcessModel
import PolyFun.Interaction.Open.OpenSyntax.Raw
import PolyFun.Interaction.Open.ScheduledOpenProcessModel
import PolyFun.Interaction.Open.ScheduledSamplerFactorization
import PolyFun.PFunctor.Basic
import PolyFun.PFunctor.Bound
import PolyFun.PFunctor.Dynamical.Behavior
import PolyFun.PFunctor.Dynamical.DynComputation.Bounded
import PolyFun.PFunctor.Dynamical.Game
import PolyFun.PFunctor.Dynamical.Run
import PolyFun.PFunctor.Dynamical.Simulation
import PolyFun.PFunctor.Free.Basic
import PolyFun.PFunctor.Free.Cursor
import PolyFun.PFunctor.Free.Cursor.Fork
import PolyFun.PFunctor.Free.HandlerMachine
import PolyFun.PFunctor.Free.Path
import PolyFun.PFunctor.Free.Path.Bounded
import PolyFun.PFunctor.Free.Path.Execution
import PolyFun.PFunctor.Free.Sigma
import PolyFun.PFunctor.Free.Support
import PolyFun.PFunctor.Free.WP
import PolyFun.PFunctor.Handler
import PolyFun.PFunctor.Handler.Instrumentation
import PolyFun.PFunctor.Handler.Normalization
import PolyFun.PFunctor.Handler.Stateful
import PolyFun.PFunctor.Lens.Basic
import PolyFun.PFunctor.Lens.Cartesian
import PolyFun.PFunctor.Lens.State
import PolyFun.PFunctor.Resumption.Truncate
import PolyFun.PFunctor.Trace
import PolyFun.PFunctor.Wiring
import PolyFun.Realizability.Instances
import PolyFun.Realizability.Quantitative.Closure
import PolyFun.Realizability.Quantitative.Polynomial
import PolyFun.Realizability.Quantitative.Resource
import PolyFun.Realizability.Representation

/-!
# Downstream surface canary

Generated by `scripts/downstream-surface.py` from `scripts/downstream-surface.json`; do not edit
by hand. Every module a tracked consumer imports is imported here through an ordinary import,
and every PolyFun-owned declaration it names is referenced, so a rename or deletion fails this
build before the consumer's pin bump discovers it. See `docs/development/compatibility.md`.
-/

@[expose] public section

/-! ## ArkLib -/

noncomputable example := @PFunctor.Lens
noncomputable example := @PFunctor.Lens.id

/-! ## VCVio -/

noncomputable example := @ITree.pure
noncomputable example := @ITree.query
noncomputable example := @Interaction.Concurrent.ProcessOver
noncomputable example := @MAlgOrdered.Triple
noncomputable example := @MAlgOrdered.restrictIic
noncomputable example := @MAlgOrdered.toWPMonad
noncomputable example := @MAlgOrdered.toWPMonad_wp
noncomputable example := @MAlgOrdered.triple_bind
noncomputable example := @MAlgOrdered.wp
noncomputable example := @MAlgOrdered.wpExc
noncomputable example := @MAlgOrdered.wpOpt
noncomputable example := @MAlgOrdered.wp_bind
noncomputable example := @MAlgOrdered.wp_map
noncomputable example := @MAlgOrdered.wp_mono
noncomputable example := @MAlgOrdered.wp_pure
noncomputable example := @MAlgOrdered.wp_restrictIic_val
noncomputable example := @MAlgRelOrdered.Anchored
noncomputable example := @MAlgRelOrdered.RelWP
noncomputable example := @MAlgRelOrdered.Triple
noncomputable example := @MAlgRelOrdered.relWP_bind_le
noncomputable example := @MAlgRelOrdered.relWP_bind_left_le
noncomputable example := @MAlgRelOrdered.relWP_bind_right_le
noncomputable example := @MAlgRelOrdered.relWP_map_left
noncomputable example := @MAlgRelOrdered.relWP_map_right
noncomputable example := @MAlgRelOrdered.relWP_mono
noncomputable example := @MAlgRelOrdered.triple_bind
noncomputable example := @MAlgRelOrdered.triple_ite
noncomputable example := @MonadAttach.bind_congr_of_forall_mem_support
noncomputable example := @MonadAttach.canReturn_bind_iff
noncomputable example := @MonadAttach.mAlgOrderedPropDemonic
noncomputable example := @MonadAttach.mem_support
noncomputable example := @MonadAttach.mem_support_bind
noncomputable example := @MonadAttach.mem_support_pure
noncomputable example := @MonadAttach.support
noncomputable example := @MonadAttach.support_bind
noncomputable example := @MonadAttach.support_map
noncomputable example := @MonadAttach.support_pure
noncomputable example := @MonadAttach.support_seq
noncomputable example := @MonadAttach.toWPMonadDemonic
noncomputable example := @MonadAttach.toWPMonadDemonic_wp
noncomputable example := @MonadAttach.wp_iff_allOutputs
noncomputable example := @MonadAttach.wp_iff_forall_support
noncomputable example := @MonadHom.id
noncomputable example := @MonadHom.mmap_map
noncomputable example := @MonadHom.ofLift
noncomputable example := @PFunctor.Closed
noncomputable example := @PFunctor.CofreeC.next
noncomputable example := @PFunctor.DecidableEq
noncomputable example := @PFunctor.DynSystem
noncomputable example := @PFunctor.DynSystem.DynComputation
noncomputable example := @PFunctor.DynSystem.DynComputation.ImplementsWithin
noncomputable example := @PFunctor.DynSystem.DynComputation.PolynomialProgramWitness
noncomputable example := @PFunctor.DynSystem.DynComputation.PolynomialProgramWitness.bind
noncomputable example := @PFunctor.DynSystem.DynComputation.PolynomialProgramWitness.congrProgram
noncomputable example :=
  @PFunctor.DynSystem.DynComputation.PolynomialProgramWitness.isQuantitativelyRealizableBy
noncomputable example :=
  @PFunctor.DynSystem.DynComputation.PolynomialProgramWitness.isTotalRollBound
noncomputable example :=
  @PFunctor.DynSystem.DynComputation.PolynomialProgramWitness.outputSizePolynomial
noncomputable example := @PFunctor.DynSystem.DynComputation.PureResourceCertificate
noncomputable example := @PFunctor.DynSystem.DynComputation.PureResourceCertificate.implements
noncomputable example := @PFunctor.DynSystem.DynComputation.PureResourceCertificate.ofPolyRealizer
noncomputable example := @PFunctor.DynSystem.DynComputation.PureResourceCertificate.polynomial
noncomputable example := @PFunctor.DynSystem.DynComputation.PureResourceCertificate.programWitness
noncomputable example := @PFunctor.DynSystem.DynComputation.PureResourceCertificate.realization
noncomputable example := @PFunctor.DynSystem.DynComputation.PureResourceCertificate.runsWithin
noncomputable example := @PFunctor.DynSystem.DynComputation.QuantitativeRealization
noncomputable example := @PFunctor.DynSystem.DynComputation.RankedResource.PotentialCertificate
noncomputable example :=
  @PFunctor.DynSystem.DynComputation.RankedResource.PotentialCertificate.resolvesInUnder
noncomputable example :=
  @PFunctor.DynSystem.DynComputation.RankedResource.PotentialCertificate.runsWithinUnder
noncomputable example :=
  @PFunctor.DynSystem.DynComputation.RankedResource.PotentialCertificate.traceCost_add_terminal_le
noncomputable example := @PFunctor.DynSystem.DynComputation.RankedResource.queryStepCost
noncomputable example := @PFunctor.DynSystem.DynComputation.RankedResource.terminalCost
noncomputable example := @PFunctor.DynSystem.DynComputation.RankedResourceCertificate
noncomputable example := @PFunctor.DynSystem.DynComputation.RankedResourceCertificate.programWitness
noncomputable example := @PFunctor.DynSystem.DynComputation.ResolvesInUnder
noncomputable example := @PFunctor.DynSystem.DynComputation.ResponseModulus
noncomputable example := @PFunctor.DynSystem.DynComputation.ResponseResourceContract
noncomputable example := @PFunctor.DynSystem.DynComputation.ResponseResourceContract.Model
noncomputable example := @PFunctor.DynSystem.DynComputation.ResponseResourceContract.Model.modulus
noncomputable example :=
  @PFunctor.DynSystem.DynComputation.ResponseResourceContract.Model.modulus_monotone
noncomputable example :=
  @PFunctor.DynSystem.DynComputation.ResponseResourceContract.Model.resourceModel
noncomputable example := @PFunctor.DynSystem.DynComputation.ResponseResourceModel
noncomputable example := @PFunctor.DynSystem.DynComputation.ResponseResourceModel.modulus
noncomputable example := @PFunctor.DynSystem.DynComputation.ResponseResourceModel.modulus_monotone
noncomputable example := @PFunctor.DynSystem.DynComputation.ofFn
noncomputable example := @PFunctor.DynSystem.closedGame
noncomputable example := @PFunctor.DynSystem.iterWith
noncomputable example := @PFunctor.DynSystem.kleisliIterate
noncomputable example := @PFunctor.DynSystem.kleisliStep
noncomputable example := @PFunctor.DynSystem.next_iterate_trajectory
noncomputable example := @PFunctor.DynSystem.pairing
noncomputable example := @PFunctor.DynSystem.stepWith
noncomputable example := @PFunctor.DynSystem.stepWith_lift
noncomputable example := @PFunctor.DynSystem.trajectory
noncomputable example := @PFunctor.DynSystem.wrap
noncomputable example := @PFunctor.DynSystem.wrap_comp
noncomputable example := @PFunctor.ExecutionCostPolynomial
noncomputable example := @PFunctor.ExecutionCostPolynomial.add
noncomputable example := @PFunctor.ExecutionCostPolynomial.add_eval_le_eval_add
noncomputable example := @PFunctor.ExecutionCostPolynomial.comp
noncomputable example := @PFunctor.ExecutionCostPolynomial.const
noncomputable example := @PFunctor.ExecutionCostPolynomial.eval
noncomputable example := @PFunctor.ExecutionCostPolynomial.eval_comp
noncomputable example := @PFunctor.ExecutionCostPolynomial.eval_const
noncomputable example := @PFunctor.ExecutionCostPolynomial.eval_mono_input
noncomputable example := @PFunctor.ExecutionCostPolynomial.eval_mono_lengths
noncomputable example := @PFunctor.ExecutionCostPolynomial.eval_ofFirstOrder
noncomputable example := @PFunctor.ExecutionCostPolynomial.eval_reindex
noncomputable example := @PFunctor.ExecutionCostPolynomial.eval_subst
noncomputable example := @PFunctor.ExecutionCostPolynomial.ofFirstOrder
noncomputable example := @PFunctor.ExecutionCostPolynomial.reindex
noncomputable example := @PFunctor.ExecutionCostPolynomial.subst
noncomputable example := @PFunctor.Fintype
noncomputable example := @PFunctor.FreeM
noncomputable example := @PFunctor.FreeM.Cursor
noncomputable example := @PFunctor.FreeM.Cursor.ForkView
noncomputable example := @PFunctor.FreeM.Cursor.ForkView.firstAnswer
noncomputable example := @PFunctor.FreeM.Cursor.ForkView.firstAnswer_mk
noncomputable example := @PFunctor.FreeM.Cursor.ForkView.firstPath
noncomputable example := @PFunctor.FreeM.Cursor.ForkView.firstPath_mk
noncomputable example := @PFunctor.FreeM.Cursor.ForkView.secondAnswer
noncomputable example := @PFunctor.FreeM.Cursor.ForkView.secondAnswer_mk
noncomputable example := @PFunctor.FreeM.Cursor.ForkView.secondPath_mk
noncomputable example := @PFunctor.FreeM.Cursor.Located
noncomputable example := @PFunctor.FreeM.Cursor.Located.fork
noncomputable example := @PFunctor.FreeM.Cursor.Located.fork_eq_map_complete
noncomputable example := @PFunctor.FreeM.Cursor.Occurrence
noncomputable example := @PFunctor.FreeM.Cursor.Occurrence.complete
noncomputable example := @PFunctor.FreeM.Cursor.Occurrence.completePath
noncomputable example := @PFunctor.FreeM.Cursor.Occurrence.trace_plug
noncomputable example := @PFunctor.FreeM.Cursor.SelectedForkView
noncomputable example := @PFunctor.FreeM.Cursor.SelectedForkView.outputs
noncomputable example := @PFunctor.FreeM.Cursor.Spine.down
noncomputable example := @PFunctor.FreeM.Cursor.Split
noncomputable example := @PFunctor.FreeM.Cursor.Split.completeFork_missing
noncomputable example := @PFunctor.FreeM.Cursor.Split.complete_found
noncomputable example := @PFunctor.FreeM.Cursor.Split.complete_missing
noncomputable example := @PFunctor.FreeM.Cursor.Split.map_completeFork_found
noncomputable example := @PFunctor.FreeM.Cursor.down
noncomputable example := @PFunctor.FreeM.Cursor.filterMapLocateAndForkAt
noncomputable example := @PFunctor.FreeM.Cursor.filterMapLocateAndForkAt_eq_bind_complete
noncomputable example := @PFunctor.FreeM.Cursor.filterMapLocateAndForkBy
noncomputable example := @PFunctor.FreeM.Cursor.filterMapLocateAndForkBy_eq_bind_complete
noncomputable example := @PFunctor.FreeM.Cursor.filterMapLocateAndForkSelected
noncomputable example :=
  @PFunctor.FreeM.Cursor.filterMapLocateAndForkSelected_eq_filterMapLocateAndForkBy
noncomputable example := @PFunctor.FreeM.Cursor.forkAt_eq_locateAndForkAt
noncomputable example := @PFunctor.FreeM.Cursor.locateAndForkAt
noncomputable example := @PFunctor.FreeM.Cursor.map_locateAndForkAt
noncomputable example := @PFunctor.FreeM.Cursor.map_locateAndForkBy
noncomputable example := @PFunctor.FreeM.Cursor.root
noncomputable example := @PFunctor.FreeM.Cursor.splitAtValid
noncomputable example := @PFunctor.FreeM.Cursor.splitAtValid_bind_complete
noncomputable example := @PFunctor.FreeM.Cursor.splitAtValid_bind_completeFork
noncomputable example := @PFunctor.FreeM.Cursor.trace_down
noncomputable example := @PFunctor.FreeM.IsRollBound
noncomputable example := @PFunctor.FreeM.Path
noncomputable example := @PFunctor.FreeM.Path.length
noncomputable example := @PFunctor.FreeM.Path.length_pullMap
noncomputable example := @PFunctor.FreeM.Path.length_pure
noncomputable example := @PFunctor.FreeM.Path.trace
noncomputable example := @PFunctor.FreeM.PathAlong
noncomputable example := @PFunctor.FreeM.RootSatisfies
noncomputable example := @PFunctor.FreeM.bind
noncomputable example := @PFunctor.FreeM.isRollBound_bind
noncomputable example := @PFunctor.FreeM.isRollBound_congr
noncomputable example := @PFunctor.FreeM.isRollBound_iff_of_map_eq
noncomputable example := @PFunctor.FreeM.isRollBound_lift_iff
noncomputable example := @PFunctor.FreeM.isRollBound_map_iff
noncomputable example := @PFunctor.FreeM.isRollBound_seq
noncomputable example := @PFunctor.FreeM.leavesSatisfyUnder_liftM
noncomputable example := @PFunctor.FreeM.leavesSatisfyUnder_map_iff
noncomputable example := @PFunctor.FreeM.lift
noncomputable example := @PFunctor.FreeM.liftBind
noncomputable example := @PFunctor.FreeM.liftBind_eq
noncomputable example := @PFunctor.FreeM.liftM
noncomputable example := @PFunctor.FreeM.liftMHom
noncomputable example := @PFunctor.FreeM.liftM_bind
noncomputable example := @PFunctor.FreeM.liftM_natural
noncomputable example := @PFunctor.FreeM.liftObj
noncomputable example := @PFunctor.FreeM.map
noncomputable example := @PFunctor.FreeM.mapLens
noncomputable example := @PFunctor.FreeM.map_liftBind
noncomputable example := @PFunctor.FreeM.map_output_withPath
noncomputable example := @PFunctor.FreeM.output
noncomputable example := @PFunctor.FreeM.outputAlong
noncomputable example := @PFunctor.FreeM.packFamily
noncomputable example := @PFunctor.FreeM.pure
noncomputable example := @PFunctor.FreeM.pure_inj
noncomputable example := @PFunctor.FreeM.reachable
noncomputable example := @PFunctor.FreeM.reachableUnder
noncomputable example := @PFunctor.FreeM.reachableUnder_bind
noncomputable example := @PFunctor.FreeM.reachableUnder_liftObj
noncomputable example := @PFunctor.FreeM.reachableUnder_mono
noncomputable example := @PFunctor.FreeM.reachable_eq_support
noncomputable example := @PFunctor.FreeM.reachable_liftM_subset
noncomputable example := @PFunctor.FreeM.run_liftM_mapHom
noncomputable example := @PFunctor.FreeM.sigmaInj
noncomputable example := @PFunctor.FreeM.support_finite
noncomputable example := @PFunctor.FreeM.support_liftObj
noncomputable example := @PFunctor.FreeM.support_map
noncomputable example := @PFunctor.FreeM.support_nonempty
noncomputable example := @PFunctor.FreeM.withPath
noncomputable example := @PFunctor.Handler
noncomputable example := @PFunctor.Handler.Stateful
noncomputable example := @PFunctor.Handler.Stateful.run
noncomputable example := @PFunctor.Handler.liftTarget
noncomputable example := @PFunctor.Handler.liftTarget_apply
noncomputable example := @PFunctor.Handler.liftTarget_self
noncomputable example := @PFunctor.Handler.postInsert
noncomputable example := @PFunctor.Handler.postInsert_apply
noncomputable example := @PFunctor.Handler.preInsert
noncomputable example := @PFunctor.Handler.withTrace
noncomputable example := @PFunctor.Handler.withTraceAppend
noncomputable example := @PFunctor.Handler.withTraceAppendBefore
noncomputable example := @PFunctor.Handler.withTraceAppendBefore_apply
noncomputable example := @PFunctor.Handler.withTraceAppendBefore_eq_preInsert
noncomputable example := @PFunctor.Handler.withTraceAppend_apply
noncomputable example := @PFunctor.Handler.withTraceAppend_eq_postInsert
noncomputable example := @PFunctor.Handler.withTraceBefore
noncomputable example := @PFunctor.Handler.withTraceBefore_apply
noncomputable example := @PFunctor.Handler.withTraceBefore_eq_preInsert
noncomputable example := @PFunctor.Handler.withTrace_apply
noncomputable example := @PFunctor.Handler.withTrace_eq_postInsert
noncomputable example := @PFunctor.Inhabited
noncomputable example := @PFunctor.Lens
noncomputable example := @PFunctor.Lens.Equiv
noncomputable example := @PFunctor.Lens.IsCartesian
noncomputable example := @PFunctor.Lens.State
noncomputable example := @PFunctor.Lens.State.IsSeparated
noncomputable example := @PFunctor.Lens.State.IsVeryWellBehaved
noncomputable example := @PFunctor.Lens.State.fst
noncomputable example := @PFunctor.Lens.State.id
noncomputable example := @PFunctor.Lens.State.mk_get
noncomputable example := @PFunctor.Lens.State.mk_put
noncomputable example := @PFunctor.Lens.State.snd
noncomputable example := @PFunctor.Lens.ext
noncomputable example := @PFunctor.Lens.id
noncomputable example := @PFunctor.Lens.sumMap
noncomputable example := @PFunctor.Obj
noncomputable example := @PFunctor.Obj.fst
noncomputable example := @PFunctor.Obj.rec
noncomputable example := @PFunctor.Obj.snd
noncomputable example := @PFunctor.QuantitativeStepClass
noncomputable example := @PFunctor.QuantitativeStepClass.PolyRealizer
noncomputable example := @PFunctor.Responder
noncomputable example := @PFunctor.Responder.equivStateHandler
noncomputable example := @PFunctor.Resumption
noncomputable example := @PFunctor.Section
noncomputable example := @PFunctor.StepClass
noncomputable example := @PFunctor.StepClass.CodeOption
noncomputable example := @PFunctor.StepClass.CodePairing
noncomputable example := @PFunctor.StepClass.CodeRetract
noncomputable example := @PFunctor.StepClass.CodeRetract.id
noncomputable example := @PFunctor.StepClass.CodeRetract.option
noncomputable example := @PFunctor.StepClass.CodeRetract.prod
noncomputable example := @PFunctor.StepClass.CodeRetract.sigma
noncomputable example := @PFunctor.StepClass.CodeRetract.sum
noncomputable example := @PFunctor.StepClass.CodeSum
noncomputable example := @PFunctor.StepClass.HasOption
noncomputable example := @PFunctor.StepClass.IsDistributive
noncomputable example := @PFunctor.Trace
noncomputable example := @PFunctor.TraceList
noncomputable example := @PFunctor.TraceList.DirectionsWithin
noncomputable example := @PFunctor.TraceList.occurrences
noncomputable example := @PFunctor.Wiring
noncomputable example := @PFunctor.map
noncomputable example := @PFunctor.monomial
noncomputable example := @PFunctor.pi
noncomputable example := @PFunctor.prod
noncomputable example := @PFunctor.sectionLens
noncomputable example := @PFunctor.selfMonomial_B
noncomputable example := @PFunctor.sigma
noncomputable example := @PFunctor.sum
