/-
Copyright (c) 2026 PolyFun Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Devon Tuma
-/
module

public import PolyFun.Interaction.UC.OpenProcessModel
public import PolyFun.Interaction.UC.SubTheory
public import PolyFun.Realizability.DynSystem
public import PolyFun.Realizability.DynSystemClosure

/-!
# Structural realizability for UC open processes

This module connects the qualitative machine-realizability layer to the
boundary-indexed UC framework.  The bridge deliberately concerns only the
structural `ProcessOver` projection of an `OpenProcess`: sampler cost,
probabilistic adequacy, activation budgets, and asymptotic bounds belong in a
downstream computational semantics such as VCVio.

The step polynomial of an open process has state, decorated-position, and path
types in different universes.  `OpenProcess.StructuralBoundary` uses
`DynSystem.ulift` to normalize them into the single universe expected by a
`StepClass`; the lift is representation-visible and therefore cannot hide a
boundary encoding choice.

There are two composition-closed views:

* `realizableSubTheory` has direct realizability as its membership predicate.
  Its construction requires `IsRealizabilityClosed`, the exact downstream
  closure contract for `map`, `par`, `wire`, and `plug`.
* `generatedRealizableSubTheory` is always available.  It is the least
  plug-closed sub-theory generated by directly realizable processes, so its
  membership records a composition derivation until direct machine closure has
  been discharged.

This distinction prevents the current qualitative bridge from claiming that
samplers or whole networks are polynomial time merely because their atoms have
admissible structural maps.
-/

public section

universe u v w w' r

namespace Interaction
namespace UC

open Concurrent

namespace OpenProcess

/-! ## Lifted boundaries and direct realizability -/

set_option linter.checkUnivs false in
/-- The universe-normalized polynomial interface exposed by open processes at
boundary `Δ`. -/
abbrev StructuralPFunctor (Party : Type u) (Δ : PortBoundary) :=
  PFunctor.ulift.{max u (w + 1), w, max v w, max v (max u (w + 1))}
    (StepOver.toPFunctor (OpenNodeContext.{u, w} Party Δ))

set_option linter.checkUnivs false in
/-- Pinned representations of the lifted decorated-step position and path-index
types at an open boundary.  The state universe `v` and move universe `w` occur
together because `DynSystem.ulift` normalizes both into
`max u v (w + 1)`; they are intentionally independent before that lift. -/
abbrev StructuralBoundary
    (C : PFunctor.StepClass.{max u v (w + 1), r})
    (Party : Type u) (Δ : PortBoundary) :=
  PFunctor.DynSystem.Boundary C
    (StructuralPFunctor.{u, v, w} Party Δ)

/-- The lifted polynomial lens implementing adaptation of an open-process
boundary. Concrete complexity classes prove its position map and partial
direction pullback admissible at their chosen boundary encodings. -/
def structuralMapLens (Party : Type u) {Δ₁ Δ₂ : PortBoundary}
    (φ : PortBoundary.Hom Δ₁ Δ₂) :
    PFunctor.Lens
      (StructuralPFunctor.{u, v, w} Party Δ₁)
      (StructuralPFunctor.{u, v, w} Party Δ₂) :=
  PFunctor.Lens.uliftMap
    (StepOver.mapContextLens (OpenNodeContext.map.{u, w} Party φ))

/-- Direct structural realizability of an open process.  The sampler is
intentionally absent: this predicate constrains the lifted `ProcessOver`
exposure and transition only. -/
abbrev IsStructurallyRealizableBy
    {m : Type w → Type w'} {Party : Type u} {Δ : PortBoundary}
    (C : PFunctor.StepClass.{max u v (w + 1), r}) [C.HasProd]
    [C.HasOption] (bd : StructuralBoundary.{u, v, w, r} C Party Δ)
    (process : OpenProcess.{u, v, w, w'} m Party Δ) : Prop :=
  PFunctor.DynSystem.IsRealizableBy C bd
    (PFunctor.DynSystem.ulift process.toProcess)

/-- An admissible lifted boundary lens transports direct structural
realizability across `OpenProcess.mapBoundary`. -/
theorem IsStructurallyRealizableBy.mapBoundary
    {m : Type w → Type w'} {Party : Type u} {Δ₁ Δ₂ : PortBoundary}
    {C : PFunctor.StepClass.{max u v (w + 1), r}} [C.HasProd]
    [C.HasOption]
    {source : StructuralBoundary.{u, v, w, r} C Party Δ₁}
    {target : StructuralBoundary.{u, v, w, r} C Party Δ₂}
    {process : OpenProcess.{u, v, w, w'} m Party Δ₁}
    {φ : PortBoundary.Hom Δ₁ Δ₂}
    (hlens : (structuralMapLens.{u, v, w} Party φ).IsDynAdmissible
      C source target)
    (h : process.IsStructurallyRealizableBy C source) :
    (process.mapBoundary φ).IsStructurallyRealizableBy C target := by
  have hsys : PFunctor.DynSystem.ulift (process.mapBoundary φ).toProcess =
      (PFunctor.DynSystem.ulift process.toProcess).wrap
        (structuralMapLens.{u, v, w} Party φ) :=
    (congrArg PFunctor.DynSystem.ulift (toProcess_mapBoundary φ process)).trans
      (PFunctor.DynSystem.ulift_wrap process.toProcess
        (StepOver.mapContextLens (OpenNodeContext.map.{u, w} Party φ)))
  unfold IsStructurallyRealizableBy
  rw [hsys]
  exact h.wrap hlens

/-! ## Direct closure contract -/

set_option linter.checkUnivs false in
/-- The lifted regrouped polynomial lens implementing scheduler interleaving
of open-process boundaries: the shared structural content of `openTheory.par`,
`openTheory.wire`, and `openTheory.plug`, which differ only in the injection
pair and scheduler node supplied. -/
def structuralInterleaveLens (Party : Type u) {Δ₁ Δ₂ Δ : PortBoundary}
    (f₁ : TypeTree.Node.ContextHom
      (OpenNodeContext.{u, w} Party Δ₁) (OpenNodeContext.{u, w} Party Δ))
    (f₂ : TypeTree.Node.ContextHom
      (OpenNodeContext.{u, w} Party Δ₂) (OpenNodeContext.{u, w} Party Δ))
    (schedulerCtx : OpenNodeContext.{u, w} Party Δ (ULift.{w, 0} Bool)) :
    PFunctor.Lens
      (PFunctor.prod (StructuralPFunctor.{u, v, w} Party Δ₁)
        (StructuralPFunctor.{u, v, w} Party Δ₂))
      (StructuralPFunctor.{u, v, w} Party Δ) :=
  PFunctor.Lens.uliftProd _ _ ⨟
    PFunctor.Lens.uliftMap (ProcessOver.interleaveLens f₁ f₂ schedulerCtx)

/-- The exact obligations needed for direct structural realizability to form a
plug-closed UC sub-theory: first-order admissibility certificates for the
boundary-adaptation lenses and for the three interleaving lenses at the pinned
boundary family.  The composite closure theorems (`par_mem`, `wire_mem`,
`plug_mem`) then follow generically through the product-state combinator
`DynSystem.IsRealizableBy.ulift_wrapChoiceProd`.

The contract mentions no processes and no samplers: it is a statement about
the boundary encodings and the step class alone. -/
class IsRealizabilityClosed (Party : Type u)
    (C : PFunctor.StepClass.{max u v (w + 1), r}) [C.HasProd] [C.HasSum]
    [C.HasOption] [C.IsDistributive]
    [C.HasULiftProd.{v, max u (w + 1)}]
    (bd : ∀ Δ, StructuralBoundary.{u, v, w, r} C Party Δ) where
  /-- Every structural boundary-adaptation lens is admissible at the pinned
  representations. The generic transport theorem then supplies map closure. -/
  mapAdmissible : ∀ {Δ₁ Δ₂ : PortBoundary}
    (φ : PortBoundary.Hom Δ₁ Δ₂),
    (structuralMapLens.{u, v, w} Party φ).IsDynAdmissible
      C (bd Δ₁) (bd Δ₂)
  /-- The parallel-composition interleaving lens is admissible. -/
  parAdmissible : ∀ (Δ₁ Δ₂ : PortBoundary),
    (structuralInterleaveLens.{u, v, w} Party
        (OpenNodeContext.inlTensor Party Δ₁ Δ₂)
        (OpenNodeContext.inrTensor Party Δ₁ Δ₂)
        (schedulerNode Party (PortBoundary.tensor Δ₁ Δ₂))).IsChoiceAdmissible
      C (bd Δ₁) (bd Δ₂) (bd (PortBoundary.tensor Δ₁ Δ₂))
  /-- The wiring interleaving lens is admissible. -/
  wireAdmissible : ∀ (Δ₁ Γ Δ₂ : PortBoundary),
    (structuralInterleaveLens.{u, v, w} Party
        (OpenNodeContext.wireLeft Party Δ₁ Γ Δ₂)
        (OpenNodeContext.wireRight Party Δ₁ Γ Δ₂)
        (schedulerNode Party (PortBoundary.tensor Δ₁ Δ₂))).IsChoiceAdmissible
      C (bd (PortBoundary.tensor Δ₁ Γ))
        (bd (PortBoundary.tensor (PortBoundary.swap Γ) Δ₂))
        (bd (PortBoundary.tensor Δ₁ Δ₂))
  /-- The plugging interleaving lens is admissible. -/
  plugAdmissible : ∀ (Δ : PortBoundary),
    (structuralInterleaveLens.{u, v, w} Party
        (OpenNodeContext.close Party Δ)
        (OpenNodeContext.close Party (PortBoundary.swap Δ))
        (schedulerNode Party PortBoundary.empty)).IsChoiceAdmissible
      C (bd Δ) (bd (PortBoundary.swap Δ)) (bd PortBoundary.empty)

namespace IsRealizabilityClosed

variable {m : Type w → Type w'} {Party : Type u}
  {C : PFunctor.StepClass.{max u v (w + 1), r}} [C.HasProd] [C.HasSum]
  [C.HasOption] [C.IsDistributive]
  [C.HasULiftProd.{v, max u (w + 1)}]
  {bd : ∀ Δ, StructuralBoundary.{u, v, w, r} C Party Δ}
  [inst : IsRealizabilityClosed.{u, v, w, r} Party C bd]
  (schedulerSampler : m (ULift.{w, 0} Bool))

/-- Parallel composition preserves direct structural realizability. -/
theorem par_mem {Δ₁ Δ₂ : PortBoundary}
    {left : OpenProcess.{u, v, w, w'} m Party Δ₁}
    {right : OpenProcess.{u, v, w, w'} m Party Δ₂}
    (h₁ : left.IsStructurallyRealizableBy C (bd Δ₁))
    (h₂ : right.IsStructurallyRealizableBy C (bd Δ₂)) :
    ((openTheory Party m schedulerSampler).par left right).IsStructurallyRealizableBy
      C (bd (PortBoundary.tensor Δ₁ Δ₂)) := by
  have hsys : PFunctor.DynSystem.ulift
      ((openTheory Party m schedulerSampler).par left right).toProcess =
      PFunctor.DynSystem.ulift
        ((left.toProcess.choiceProd right.toProcess).wrap
          (ProcessOver.interleaveLens
            (OpenNodeContext.inlTensor Party Δ₁ Δ₂)
            (OpenNodeContext.inrTensor Party Δ₁ Δ₂)
            (schedulerNode Party (PortBoundary.tensor Δ₁ Δ₂)))) :=
    congrArg PFunctor.DynSystem.ulift
      ((toProcess_interleave left right _ _ _ schedulerSampler).trans
        (ProcessOver.interleave_eq_wrap_choiceProd _ _ _ _ _))
  unfold IsStructurallyRealizableBy
  rw [hsys]
  exact h₁.ulift_wrapChoiceProd h₂ (inst.parAdmissible Δ₁ Δ₂)

/-- Wiring a shared boundary preserves direct structural realizability. -/
theorem wire_mem {Δ₁ Γ Δ₂ : PortBoundary}
    {left : OpenProcess.{u, v, w, w'} m Party (PortBoundary.tensor Δ₁ Γ)}
    {right : OpenProcess.{u, v, w, w'} m Party
      (PortBoundary.tensor (PortBoundary.swap Γ) Δ₂)}
    (h₁ : left.IsStructurallyRealizableBy C (bd (PortBoundary.tensor Δ₁ Γ)))
    (h₂ : right.IsStructurallyRealizableBy C
      (bd (PortBoundary.tensor (PortBoundary.swap Γ) Δ₂))) :
    ((openTheory Party m schedulerSampler).wire left right).IsStructurallyRealizableBy
      C (bd (PortBoundary.tensor Δ₁ Δ₂)) := by
  have hsys : PFunctor.DynSystem.ulift
      ((openTheory Party m schedulerSampler).wire left right).toProcess =
      PFunctor.DynSystem.ulift
        ((left.toProcess.choiceProd right.toProcess).wrap
          (ProcessOver.interleaveLens
            (OpenNodeContext.wireLeft Party Δ₁ Γ Δ₂)
            (OpenNodeContext.wireRight Party Δ₁ Γ Δ₂)
            (schedulerNode Party (PortBoundary.tensor Δ₁ Δ₂)))) :=
    congrArg PFunctor.DynSystem.ulift
      ((toProcess_interleave left right _ _ _ schedulerSampler).trans
        (ProcessOver.interleave_eq_wrap_choiceProd _ _ _ _ _))
  unfold IsStructurallyRealizableBy
  rw [hsys]
  exact h₁.ulift_wrapChoiceProd h₂ (inst.wireAdmissible Δ₁ Γ Δ₂)

/-- Closing an allowed process against an allowed context preserves direct
structural realizability. -/
theorem plug_mem {Δ : PortBoundary}
    {process : OpenProcess.{u, v, w, w'} m Party Δ}
    {context : OpenProcess.{u, v, w, w'} m Party (PortBoundary.swap Δ)}
    (h₁ : process.IsStructurallyRealizableBy C (bd Δ))
    (h₂ : context.IsStructurallyRealizableBy C (bd (PortBoundary.swap Δ))) :
    ((openTheory Party m schedulerSampler).plug process context).IsStructurallyRealizableBy
      C (bd PortBoundary.empty) := by
  have hsys : PFunctor.DynSystem.ulift
      ((openTheory Party m schedulerSampler).plug process context).toProcess =
      PFunctor.DynSystem.ulift
        ((process.toProcess.choiceProd context.toProcess).wrap
          (ProcessOver.interleaveLens
            (OpenNodeContext.close Party Δ)
            (OpenNodeContext.close Party (PortBoundary.swap Δ))
            (schedulerNode Party PortBoundary.empty))) :=
    congrArg PFunctor.DynSystem.ulift
      ((toProcess_interleave process context _ _ _ schedulerSampler).trans
        (ProcessOver.interleave_eq_wrap_choiceProd _ _ _ _ _))
  unfold IsStructurallyRealizableBy
  rw [hsys]
  exact h₁.ulift_wrapChoiceProd h₂ (inst.plugAdmissible Δ)

end IsRealizabilityClosed

end OpenProcess

/-! ## Composition-closed sub-theories -/

/-- Directly structurally realizable open processes as a UC sub-theory.
Construction is available exactly when the chosen boundary encodings and step
class satisfy `OpenProcess.IsRealizabilityClosed`. -/
@[expose]
def realizableSubTheory
    {m : Type w → Type w'} (Party : Type u)
    (C : PFunctor.StepClass.{max u v (w + 1), r}) [C.HasProd] [C.HasSum]
    [C.HasOption] [C.IsDistributive]
    [C.HasULiftProd.{v, max u (w + 1)}]
    (bd : ∀ Δ, OpenProcess.StructuralBoundary.{u, v, w, r} C Party Δ)
    (schedulerSampler : m (ULift.{w, 0} Bool))
    [OpenProcess.IsRealizabilityClosed.{u, v, w, r} Party C bd] :
    SubTheory (openTheory.{u, v, w, w'} Party m schedulerSampler) where
  mem {Δ} process := process.IsStructurallyRealizableBy C (bd Δ)
  mem_map φ h := h.mapBoundary
    (OpenProcess.IsRealizabilityClosed.mapAdmissible
      (Party := Party) (C := C) (bd := bd) φ)
  mem_par hleft hright :=
    OpenProcess.IsRealizabilityClosed.par_mem schedulerSampler hleft hright
  mem_wire hleft hright :=
    OpenProcess.IsRealizabilityClosed.wire_mem schedulerSampler hleft hright

instance isPlugClosed_realizableSubTheory
    {m : Type w → Type w'} (Party : Type u)
    (C : PFunctor.StepClass.{max u v (w + 1), r}) [C.HasProd] [C.HasSum]
    [C.HasOption] [C.IsDistributive]
    [C.HasULiftProd.{v, max u (w + 1)}]
    (bd : ∀ Δ, OpenProcess.StructuralBoundary.{u, v, w, r} C Party Δ)
    (schedulerSampler : m (ULift.{w, 0} Bool))
    [OpenProcess.IsRealizabilityClosed.{u, v, w, r} Party C bd] :
    (realizableSubTheory Party C bd schedulerSampler).IsPlugClosed where
  mem_plug hprocess hcontext :=
    OpenProcess.IsRealizabilityClosed.plug_mem schedulerSampler
      hprocess hcontext

/-- The always-available plug-closed sub-theory generated by directly
structurally realizable open processes.  Unlike `realizableSubTheory`, a member
may carry a composition derivation rather than one assembled machine witness. -/
@[expose]
def generatedRealizableSubTheory
    {m : Type w → Type w'} (Party : Type u)
    (C : PFunctor.StepClass.{max u v (w + 1), r}) [C.HasProd]
    [C.HasOption]
    (bd : ∀ Δ, OpenProcess.StructuralBoundary.{u, v, w, r} C Party Δ)
    (schedulerSampler : m (ULift.{w, 0} Bool)) :
    SubTheory (openTheory.{u, v, w, w'} Party m schedulerSampler) :=
  SubTheory.plugGenerated _ fun Δ process =>
    process.IsStructurallyRealizableBy C (bd Δ)

/-- Every directly structurally realizable process is a generator of the
generated realizability sub-theory. -/
theorem mem_generatedRealizableSubTheory
    {m : Type w → Type w'} {Party : Type u}
    {C : PFunctor.StepClass.{max u v (w + 1), r}} [C.HasProd]
    [C.HasOption]
    {bd : ∀ Δ, OpenProcess.StructuralBoundary.{u, v, w, r} C Party Δ}
    {schedulerSampler : m (ULift.{w, 0} Bool)}
    {Δ : PortBoundary} {process : OpenProcess.{u, v, w, w'} m Party Δ}
    (h : process.IsStructurallyRealizableBy C (bd Δ)) :
    (generatedRealizableSubTheory Party C bd schedulerSampler).mem process :=
  SubTheory.PlugGenerated.base h

/-- Once direct realizability is composition-closed, the generated and direct
views have the same allowed systems in the direction needed by contextual
security: every generated member has a direct machine witness. -/
theorem generatedRealizableSubTheory_le_realizableSubTheory
    {m : Type w → Type w'} (Party : Type u)
    (C : PFunctor.StepClass.{max u v (w + 1), r}) [C.HasProd] [C.HasSum]
    [C.HasOption] [C.IsDistributive]
    [C.HasULiftProd.{v, max u (w + 1)}]
    (bd : ∀ Δ, OpenProcess.StructuralBoundary.{u, v, w, r} C Party Δ)
    (schedulerSampler : m (ULift.{w, 0} Bool))
    [OpenProcess.IsRealizabilityClosed.{u, v, w, r} Party C bd] :
    generatedRealizableSubTheory Party C bd schedulerSampler ≤
      realizableSubTheory Party C bd schedulerSampler :=
  by
    unfold generatedRealizableSubTheory
    apply SubTheory.plugGenerated_le
    intro _ _ h
    exact h

/-- Under the direct closure contract the generated and direct sub-theories
allow exactly the same systems. -/
theorem generatedRealizableSubTheory_eq_realizableSubTheory
    {m : Type w → Type w'} (Party : Type u)
    (C : PFunctor.StepClass.{max u v (w + 1), r}) [C.HasProd] [C.HasSum]
    [C.HasOption] [C.IsDistributive]
    [C.HasULiftProd.{v, max u (w + 1)}]
    (bd : ∀ Δ, OpenProcess.StructuralBoundary.{u, v, w, r} C Party Δ)
    (schedulerSampler : m (ULift.{w, 0} Bool))
    [OpenProcess.IsRealizabilityClosed.{u, v, w, r} Party C bd] :
    generatedRealizableSubTheory Party C bd schedulerSampler =
      realizableSubTheory Party C bd schedulerSampler :=
  SubTheory.ext fun W =>
    ⟨fun h => generatedRealizableSubTheory_le_realizableSubTheory
        Party C bd schedulerSampler W h,
      fun h => mem_generatedRealizableSubTheory h⟩

end UC
end Interaction
