/-
Copyright (c) 2026 PolyFun Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Devon Tuma
-/

module

import all PolyFun.Interaction.UC.EmulatesWithin
public import PolyFun.Interaction.UC.EmulatesWithin
public import PolyFun.Interaction.UC.OpenProcessEmulates
public import PolyFun.Interaction.UC.OpenSyntax.AtomSubTheory

/-!
# Sub-theory examples

Checks that the allowed-systems layer behaves as intended:

* the lattice operations synthesize their mixins,
* relativizing to `SubTheory.top` recovers the unrelativized judgments,
* the relativized composition suite elaborates on both the free syntax model
  and the process-backed `openTheory`,
* a sub-theory generated by allowed atoms transfers along interpretation, and
* the unrelativized suite is untouched.
-/

@[expose] public section

universe u v w w'

namespace Interaction.UC.SubTheoryExamples

/-! ### Lattice structure and mixin synthesis -/

section Lattice

variable {T : OpenTheory.{u}} (D D₁ D₂ : SubTheory T)

/-- The class allowing everything is plug-closed without any assumption on the
theory. -/
example : (SubTheory.top T).IsPlugClosed := inferInstance

/-- A meet of plug-closed classes is plug-closed. -/
example [D₁.IsPlugClosed] [D₂.IsPlugClosed] : (SubTheory.inf D₁ D₂).IsPlugClosed := inferInstance

/-- A generated class is plug-closed unconditionally: building a closed system
needs no factorization law. -/
example (G : ∀ Δ : PortBoundary, T.Obj Δ → Prop) :
    (SubTheory.generated T G).IsPlugClosed := inferInstance

/-- Strict plug/wire factorization gives *every* sub-theory plug-closure, so
instance synthesis needs no help on a compact-closed theory. -/
example {S : OpenTheory.{u}} [OpenTheory.HasPlugWireFactor S] (E : SubTheory S) :
    E.IsPlugClosed := inferInstance

/-- Meets are lower bounds. -/
example : SubTheory.inf D₁ D₂ ≤ D₁ := SubTheory.inf_le_left D₁ D₂

/-- Everything is below the top class. -/
example : D ≤ SubTheory.top T := SubTheory.le_top D

end Lattice

/-! ### Relativizing to `top` is a no-op -/

section Conservativity

variable {T : OpenTheory.{u}} {Δ : PortBoundary} {Obs : Observation T} {real ideal : T.Obj Δ}

/-- Emulation against every allowed context, where everything is allowed, is
emulation. -/
example : EmulatesWithin (SubTheory.top T) real ideal Obs ↔ Emulates real ideal Obs :=
  emulatesWithin_top_iff

/-- UC security relativized to the top class is UC security. -/
example {SimSpace : Type*} {simulate : SimSpace → T.Plug Δ → T.Plug Δ} :
    UCSecureWithin (SubTheory.top T) real ideal Obs SimSpace simulate ↔
      UCSecure real ideal Obs SimSpace simulate :=
  ucSecureWithin_top_iff

/-- Any unrelativized emulation weakens to any allowed class. -/
example (D : SubTheory T) (h : Emulates real ideal Obs) : EmulatesWithin D real ideal Obs :=
  h.toEmulatesWithin D

end Conservativity

/-! ### The relativized composition suite on the free syntax model -/

section FreeModel

variable {Atom : PortBoundary → Type u} {Obs : Observation (OpenSyntax.Expr.theory Atom)}
    {D : SubTheory (OpenSyntax.Expr.theory Atom)}

/-- Parallel composition, relativized. Both untouched components must be
allowed — the hypotheses a categorical account of UC imposes by convention. -/
example {Δ₁ Δ₂ : PortBoundary}
    {real₁ ideal₁ : (OpenSyntax.Expr.theory Atom).Obj Δ₁}
    {real₂ ideal₂ : (OpenSyntax.Expr.theory Atom).Obj Δ₂}
    (h₁ : EmulatesWithin D real₁ ideal₁ Obs) (h₂ : EmulatesWithin D real₂ ideal₂ Obs)
    (hReal₂ : D.mem real₂) (hIdeal₁ : D.mem ideal₁) :
    EmulatesWithin D ((OpenSyntax.Expr.theory Atom).par real₁ real₂)
      ((OpenSyntax.Expr.theory Atom).par ideal₁ ideal₂) Obs :=
  EmulatesWithin.par_compose h₁ h₂ hReal₂ hIdeal₁

/-- Wired composition, relativized. -/
example {Δ₁ Γ Δ₂ : PortBoundary}
    {real₁ ideal₁ : (OpenSyntax.Expr.theory Atom).Obj (PortBoundary.tensor Δ₁ Γ)}
    {real₂ ideal₂ :
      (OpenSyntax.Expr.theory Atom).Obj (PortBoundary.tensor (PortBoundary.swap Γ) Δ₂)}
    (h₁ : EmulatesWithin D real₁ ideal₁ Obs) (h₂ : EmulatesWithin D real₂ ideal₂ Obs)
    (hReal₂ : D.mem real₂) (hIdeal₁ : D.mem ideal₁) :
    EmulatesWithin D ((OpenSyntax.Expr.theory Atom).wire real₁ real₂)
      ((OpenSyntax.Expr.theory Atom).wire ideal₁ ideal₂) Obs :=
  EmulatesWithin.wire_compose h₁ h₂ hReal₂ hIdeal₁

/-- **No-regression canary.** The unrelativized suite is unchanged and still
reaches the free model by synthesis alone. -/
example {Δ₁ Δ₂ : PortBoundary}
    {real₁ ideal₁ : (OpenSyntax.Expr.theory Atom).Obj Δ₁}
    {real₂ ideal₂ : (OpenSyntax.Expr.theory Atom).Obj Δ₂}
    (h₁ : Emulates real₁ ideal₁ Obs) (h₂ : Emulates real₂ ideal₂ Obs) :
    Emulates ((OpenSyntax.Expr.theory Atom).par real₁ real₂)
      ((OpenSyntax.Expr.theory Atom).par ideal₁ ideal₂) Obs :=
  Emulates.par_compose h₁ h₂

end FreeModel

/-! ### The relativized `plug` theorem on the process model

`openTheory` has no strict factorization, so it reaches these through
`Observation.IsSchedulingInsensitive` rather than
`OpenTheory.HasPlugWireFactor`. -/

section ProcessModel

variable (Party : Type u) (m : Type w → Type w') [Monad m]
    (schedulerSampler : m (ULift.{w, 0} Bool))
    (Obs : Observation (openTheory.{u, v, w, w'} Party m schedulerSampler))
    [Observation.IsSchedulingInsensitive Obs]
    (D : SubTheory (openTheory.{u, v, w, w'} Party m schedulerSampler))

example {Δ : PortBoundary}
    {real ideal : (openTheory.{u, v, w, w'} Party m schedulerSampler).Obj Δ}
    {K_real K_ideal : (openTheory.{u, v, w, w'} Party m schedulerSampler).Plug Δ}
    (hProt : EmulatesWithin D real ideal Obs) (hEnv : EmulatesWithin D K_real K_ideal Obs)
    (hKreal : D.mem K_real) (hIdeal : D.mem ideal) :
    Obs.rel ((openTheory.{u, v, w, w'} Party m schedulerSampler).close real K_real)
      ((openTheory.{u, v, w, w'} Party m schedulerSampler).close ideal K_ideal) :=
  EmulatesWithin.plug_compose hProt hEnv hKreal hIdeal

end ProcessModel

/-! ### A generated sub-theory over a toy signature -/

section Atoms

/-- A two-generator signature: one component we are willing to use and one we
are not. -/
inductive ToyAtom : PortBoundary → Type where
  /-- An allowed primitive component at boundary `Δ`. -/
  | good (Δ : PortBoundary) : ToyAtom Δ
  /-- A forbidden primitive component at boundary `Δ`. -/
  | bad (Δ : PortBoundary) : ToyAtom Δ

/-- The allowed-atom predicate: `good` yes, `bad` no. -/
def toyAllowed : ∀ {Δ : PortBoundary}, ToyAtom Δ → Prop
  | _, .good _ => True
  | _, .bad _ => False

/-- Abbreviation for the syntactic theory over the toy signature. -/
abbrev ToyTheory : OpenTheory.{1} := OpenSyntax.Expr.theory ToyAtom

/-- The generated class is structural: it contains the unit and every identity
wire, found by synthesis. -/
example : (OpenSyntax.atomSubTheory ToyAtom toyAllowed).IsStructural := inferInstance

/-- An allowed atom is an allowed system. -/
example (Δ : PortBoundary) :
    (OpenSyntax.atomSubTheory ToyAtom toyAllowed).mem
      (OpenSyntax.Expr.atom (ToyAtom.good Δ)) :=
  OpenSyntax.atomSubTheory.mem_atom ToyAtom toyAllowed trivial

/-- A network of allowed atoms is allowed. This is the closure the whole
layer exists to supply. -/
example (Δ₁ Δ₂ : PortBoundary) :
    (OpenSyntax.atomSubTheory ToyAtom toyAllowed).mem
      (ToyTheory.par (OpenSyntax.Expr.atom (ToyAtom.good Δ₁))
        (OpenSyntax.Expr.atom (ToyAtom.good Δ₂))) :=
  (OpenSyntax.atomSubTheory ToyAtom toyAllowed).mem_par
    (OpenSyntax.atomSubTheory.mem_atom ToyAtom toyAllowed trivial)
    (OpenSyntax.atomSubTheory.mem_atom ToyAtom toyAllowed trivial)

/-- Plugging an allowed system against an allowed context stays allowed. -/
example (Δ : PortBoundary) :
    (OpenSyntax.atomSubTheory ToyAtom toyAllowed).mem
      (ToyTheory.plug (OpenSyntax.Expr.atom (ToyAtom.good Δ))
        (OpenSyntax.Expr.atom (ToyAtom.good (PortBoundary.swap Δ)))) :=
  SubTheory.IsPlugClosed.mem_plug
    (OpenSyntax.atomSubTheory.mem_atom ToyAtom toyAllowed trivial)
    (OpenSyntax.atomSubTheory.mem_atom ToyAtom toyAllowed trivial)

/-- The forbidden atom really is forbidden. -/
example (Δ : PortBoundary) : ¬ toyAllowed (ToyAtom.bad Δ) := id

/-- Allowing strictly more atoms gives a larger class. -/
example : OpenSyntax.atomSubTheory ToyAtom toyAllowed ≤
    OpenSyntax.atomSubTheory ToyAtom (fun _ => True) :=
  OpenSyntax.atomSubTheory.mono ToyAtom fun _ _ => trivial

/-- **The transfer theorem.** Interpreting a network of allowed atoms into any
target class that accepts the allowed atoms lands inside that class. Taken at
the identity interpretation, it says the generated class is closed under
everything the theory can build. -/
example {Δ : PortBoundary} {e : OpenSyntax.Expr ToyAtom Δ}
    (he : (OpenSyntax.atomSubTheory ToyAtom toyAllowed).mem e) :
    (OpenSyntax.atomSubTheory ToyAtom toyAllowed).mem
      (e.interpret ToyTheory OpenSyntax.Expr.atom) :=
  OpenSyntax.mem_interpret_of_atoms ToyAtom toyAllowed
    (OpenSyntax.atomSubTheory ToyAtom toyAllowed) OpenSyntax.Expr.atom
    (fun _ ha => OpenSyntax.atomSubTheory.mem_atom ToyAtom toyAllowed ha) he

/-- The same statement as an inclusion of sub-theories. -/
example : OpenSyntax.atomSubTheory ToyAtom toyAllowed ≤
    OpenSyntax.interpretSubTheory ToyAtom
      (OpenSyntax.atomSubTheory ToyAtom toyAllowed) OpenSyntax.Expr.atom :=
  OpenSyntax.atomSubTheory_le_interpretSubTheory ToyAtom toyAllowed _ _
    fun _ ha => OpenSyntax.atomSubTheory.mem_atom ToyAtom toyAllowed ha

end Atoms

end Interaction.UC.SubTheoryExamples
