/-
Copyright (c) 2026 PolyFun Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Devon Tuma
-/

module

public import Examples.Parliament.Minutes.History

/-! # Typed draft minutes derived from contextual action receipts

The bounded editorial policy is explicit in `recordAction`. A lack of a second is
not a lost vote. A withdrawal before statement is not a recorded assembly action.
-/

@[expose] public section

namespace Parliament

/-- How a resolved question was decided; consent never invents a tally. -/
inductive DecisionMethod where
  | counted (tally : Tally)
  | consent
  deriving DecidableEq

/-- Recordable actions, retaining the exact question version at their boundary. -/
inductive MinuteAction (D : MotionDomain) where
  | opened
  | decided (question : Question D) (adopted : Bool) (method : DecisionMethod)
  | notSeconded (question : Question D)
  | withdrawn (question : Question D)
  | ruled (request : Nat) (issue : IssueKind) (answer : Ruling)
  | appealResolved (request : Nat) (sustained : Bool)
  | suspended (question : Question D) (disposition : Disposition)
  | resumed (question : Question D)
  | expired (question : Question D)
  | recessed (untilSecond : Nat)
  | adjourned
  deriving DecidableEq

/-- A recordable action with its chronological and source-event coordinates. -/
structure MinuteEntry (D : MotionDomain) where
  /-- Meeting to which the action belongs. -/
  meeting : Nat
  /-- Session in which the action occurred. -/
  session : Nat
  /-- Supplied civil date at the action boundary. -/
  date : Date
  /-- Supplied within-day clock reading. -/
  second : Nat
  /-- Accepted transaction revision. -/
  revision : Nat
  /-- Zero-based index within that transaction's emitted events. -/
  eventIndex : Nat
  /-- Typed action; speech text and individual ballots have no constructor. -/
  action : MinuteAction D
  deriving DecidableEq

variable {D : MotionDomain}

/-- Recover a question's live wording from the pending series. -/
def pendingWording (s : AssemblyState D) (id : QuestionId) : Option (Question D) :=
  s.pending.find? (fun q => q.id == id)

/-- Recover the main wording of suspended business before restoration or expiry. -/
def suspendedWording (s : AssemblyState D) (id : QuestionId) : Option (Question D) :=
  (s.suspended.flatMap (·.questions)).find? (fun q => q.id == id)

/-- The editorial policy uses the accepted command and source state, not just a bare event. -/
def recordAction (s : AssemblyState D) (command : Command D) : Event → Option (MinuteAction D)
  | .opened .. => some .opened
  | .decided id adopted tally =>
    match command with
    | .announce _ => (pendingWording s id).map (fun q => .decided q adopted (.counted tally))
    | .lackSecond _ =>
      (s.proposal.filter (fun q => q.id == id)).map .notSeconded
    | _ => none
  | .consentGranted id =>
    (pendingWording s id).map (fun q => .decided q true .consent)
  | .withdrawn id => (pendingWording s id).map .withdrawn
  | .ruled id answer =>
    (s.judgment.filter (fun r => r.id == id)).map (fun r => .ruled id r.issue answer)
  | .appealResolved id sustained => some (.appealResolved id sustained)
  | .suspended id disposition =>
    (pendingWording s id).map (fun q => .suspended q disposition)
  | .resumed id => (suspendedWording s id).map .resumed
  | .expired id => (suspendedWording s id).map .expired
  | .recessed untilSecond => some (.recessed untilSecond)
  | .adjourned _ => some .adjourned
  | _ => none

/-- Attach the successor boundary and event index to a contextual action. -/
def recordEntry (before after : AssemblyState D) (command : Command D)
    (item : Nat × Event) : Option (MinuteEntry D) :=
  (recordAction before command item.2).map fun action =>
    ⟨after.calendar.meeting, after.calendar.session, after.calendar.today,
      after.nowSecond, after.revision, item.1, action⟩

/-- The document fragment generated by one accepted transaction. -/
def receiptEntries {rules : Rules} {s : AssemblyState D} (input : EnabledInput rules s) :
    List (MinuteEntry D) :=
  input.events.zipIdx.map (fun (event, index) => (index, event)) |>.filterMap
    (recordEntry s input.next input.command)

/-- Ordered editorial inference: omit precisely nonrecordable events, retain every recordable
one. -/
inductive Records (before after : AssemblyState D) (command : Command D) :
    List (Nat × Event) → List (MinuteEntry D) → Prop where
  | nil : Records before after command [] []
  | skip {item rest entries} (absent : recordEntry before after command item = none)
      (tail : Records before after command rest entries) :
      Records before after command (item :: rest) entries
  | retain {item rest entry entries} (present : recordEntry before after command item = some entry)
      (tail : Records before after command rest entries) :
      Records before after command (item :: rest) (entry :: entries)

theorem records_iff (before after : AssemblyState D) (command : Command D)
    (items : List (Nat × Event)) (entries : List (MinuteEntry D)) :
    Records before after command items entries ↔
      items.filterMap (recordEntry before after command) = entries := by
  constructor
  · intro h
    induction h with
    | nil => rfl
    | skip h _ ih => simp [h, ih]
    | retain h _ ih => simp [h, ih]
  · intro h
    subst entries
    induction items with
    | nil => exact .nil
    | cons item rest ih =>
      cases he : recordEntry before after command item with
      | none => simpa [he] using Records.skip he ih
      | some entry => simpa [he] using Records.retain he ih

theorem receiptEntries_records {rules : Rules} {s : AssemblyState D}
    (input : EnabledInput rules s) :
    Records s input.next input.command
      (input.events.zipIdx.map (fun (event, index) => (index, event))) (receiptEntries input) :=
  (records_iff _ _ _ _ _).mpr rfl

/-- All recordable actions of a certified history in execution order. -/
def History.entries {rules : Rules} {initial state : AssemblyState D} :
    History rules initial state → List (MinuteEntry D)
  | .nil => []
  | .snoc past input => past.entries ++ receiptEntries input

/-- Documents exactly account for each receipt, in chronological order. -/
inductive RecordsHistory {rules : Rules} {initial : AssemblyState D} :
    {state : AssemblyState D} → History rules initial state → List (MinuteEntry D) → Prop where
  | nil : RecordsHistory .nil []
  | snoc {state : AssemblyState D} {past : History rules initial state} {entries fragment}
      (previous : RecordsHistory past entries) (input : EnabledInput rules state)
      (recorded : Records state input.next input.command
        (input.events.zipIdx.map (fun (event, index) => (index, event))) fragment) :
      RecordsHistory (.snoc past input) (entries ++ fragment)

theorem History.entries_records {rules : Rules} {initial state : AssemblyState D}
    (history : History rules initial state) : RecordsHistory history history.entries := by
  induction history with
  | nil => exact .nil
  | snoc past input ih => exact .snoc ih input (receiptEntries_records input)

theorem RecordsHistory.unique {rules : Rules} {initial state : AssemblyState D}
    {history : History rules initial state} {entries : List (MinuteEntry D)}
    (h : RecordsHistory history entries) : entries = history.entries := by
  induction h with
  | nil => rfl
  | snoc previous input recorded ih =>
    simp only [History.entries, receiptEntries, ← ih, (records_iff _ _ _ _ _).mp recorded]

/-- Typed unapproved minutes for one meeting of a certified journal. -/
abbrev DraftMinutes {rules : Rules} (journal : Journal D rules) (meeting : Nat) :=
  { entries : List (MinuteEntry D) //
    entries = journal.history.entries.filter (fun entry => entry.meeting == meeting) }

/-- Chronological record of the meeting's modeled actions. -/
def DraftMinutes.entries {rules : Rules} {journal : Journal D rules} {meeting : Nat}
    (draft : DraftMinutes journal meeting) : List (MinuteEntry D) := draft.val

theorem DraftMinutes.faithful {rules : Rules} {journal : Journal D rules} {meeting : Nat}
    (draft : DraftMinutes journal meeting) :
    draft.entries = journal.history.entries.filter (fun entry => entry.meeting == meeting) :=
  draft.property

/-- Produce a draft from a certified journal, never from unauthenticated event claims. -/
def draftMinutes {rules : Rules} (journal : Journal D rules) (meeting : Nat) :
    DraftMinutes journal meeting := ⟨_, rfl⟩

/-- Pending wording is reported separately from completed actions. -/
def unresolved {rules : Rules} (journal : Journal D rules) : List (Question D) :=
  journal.state.pending ++ journal.state.proposal.toList ++
    journal.state.heldProposal.toList ++ journal.state.suspended.flatMap (·.questions) ++
    journal.state.review.toList.flatMap (fun r => r.proposal.toList)

theorem draftMinutes_accept {rules : Rules} (journal : Journal D rules)
    (input : EnabledInput rules journal.state) (meeting : Nat) :
    (draftMinutes (journal.accept input) meeting).entries =
      (draftMinutes journal meeting).entries ++
        (receiptEntries input).filter (fun entry => entry.meeting == meeting) := by
  simp [draftMinutes, DraftMinutes.entries, Journal.accept, History.entries]

theorem recordAction_speech (s : AssemblyState D) (command : Command D)
    (question : QuestionId) (member : MemberId) :
    recordAction s command (.spoke question member) = none := rfl

theorem recordAction_ballot (s : AssemblyState D) (command : Command D)
    (question : QuestionId) (member : MemberId) (choice : Vote) :
    recordAction s command (.voteCast question member choice) = none := rfl

end Parliament
