#!/usr/bin/env python3
"""Pin the PolyFun surface that downstream consumers import and name.

`scripts/downstream-surface.json` records, per consumer, the PolyFun-owned modules it imports
and the PolyFun-owned declarations it names. `PolyFunTest/Downstream/Surface.lean` is generated
from that file: one ordinary `import` per module and one `example := @name` per declaration, so
a rename or deletion in PolyFun fails the test build before a consumer's pin bump discovers it.

    python3 scripts/downstream-surface.py check
        Regenerate the Lean canary from the JSON and fail if the tracked file differs.
    python3 scripts/downstream-surface.py refresh --vcvio ../VCVio --arklib ../ArkLib
        Rescan the consumer checkouts, rewrite the JSON, and regenerate the canary.

`refresh` is a heuristic scan of import lines and qualified identifiers under PolyFun-owned
namespace roots; it canonicalizes imports of `deprecated_module` shims to their replacement and
keeps a name only when its last component is declared somewhere in PolyFun's production
sources. The Lean build is the ground truth: prune the JSON when a recorded name no longer
exists, and refresh it from the consumer's migration branch when the consumer moves.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(subprocess.check_output(
    ["git", "rev-parse", "--show-toplevel"], text=True).strip())
SURFACE_JSON = REPO_ROOT / "scripts" / "downstream-surface.json"
CANARY = REPO_ROOT / "PolyFunTest" / "Downstream" / "Surface.lean"
PRODUCTION_ROOTS = ("PolyFun", "ToCslib", "ComplexityBackends")
MODULE_ROOTS = ("PolyFun", "ToCslib", "ComplexityBackends")
NAME_ROOTS = (
    "PFunctor", "IPFunctor", "ITree", "MonadHom", "NatHom", "MonadAttach", "ExactMonadAttach",
    "MAlgOrdered", "MAlgRelOrdered", "Interaction.Basic", "Interaction.TwoParty",
    "Interaction.Multiparty", "Interaction.Concurrent", "Interaction.Open",
    "Interaction.Execution", "Interaction.Interface", "Control", "ComplexityBackends", "ToCslib",
)
IMPORT_RE = re.compile(
    r"^\s*(?:public\s+)?(?:meta\s+)?import(?:\s+all)?\s+((?:%s)\.[A-Za-z0-9_.]+)"
    % "|".join(MODULE_ROOTS), re.M)
NAME_RE = re.compile(
    r"(?<![A-Za-z0-9_.'])((?:%s)\.[A-Za-z0-9_.']+)" % "|".join(re.escape(r) for r in NAME_ROOTS))
DECL_RE = re.compile(
    r"^\s*(?:@\[[^\]]*\]\s*)*(?:public\s+|private\s+|protected\s+|noncomputable\s+|"
    r"scoped\s+|nonrec\s+)*(?:def|theorem|lemma|abbrev|structure|class|inductive|instance|"
    r"opaque|axiom)\s+([A-Za-z_][A-Za-z0-9_']*)", re.M)
HEADER = '''/-
Copyright (c) 2026 PolyFun Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Devon Tuma
-/

module

'''
DOCSTRING = '''
/-!
# Downstream surface canary

Generated by `scripts/downstream-surface.py` from `scripts/downstream-surface.json`; do not edit
by hand. Every module a tracked consumer imports is imported here through an ordinary import,
and every PolyFun-owned declaration it names is referenced, so a rename or deletion fails this
build before the consumer's pin bump discovers it. See `docs/development/compatibility.md`.
-/

@[expose] public section
'''


def lean_files(root: Path) -> list[Path]:
    return [p for p in root.rglob("*.lean") if ".lake" not in p.parts]


def shim_targets() -> dict[str, str]:
    """Map every `deprecated_module` shim to the module it re-exports."""
    targets: dict[str, str] = {}
    for root in PRODUCTION_ROOTS:
        for path in lean_files(REPO_ROOT / root):
            text = path.read_text()
            if not re.search(r"^deprecated_module(\s|$)", text, re.M):
                continue
            imports = re.findall(r"^public import ([A-Za-z0-9_.]+)", text, re.M)
            if len(imports) == 1:
                module = ".".join(path.relative_to(REPO_ROOT).with_suffix("").parts)
                targets[module] = imports[0]
    return targets


def declared_short_names() -> set[str]:
    names: set[str] = set()
    for root in PRODUCTION_ROOTS:
        for path in lean_files(REPO_ROOT / root):
            names.update(DECL_RE.findall(path.read_text()))
    return names


def module_exists(module: str) -> bool:
    return (REPO_ROOT / Path(*module.split("."))).with_suffix(".lean").is_file()


def scan_consumer(root: Path, own_roots: set[str]) -> tuple[list[str], list[str]]:
    shims = shim_targets()
    short_names = declared_short_names()
    modules: set[str] = set()
    names: set[str] = set()
    own_decls: set[str] = set()
    texts = []
    for path in lean_files(root):
        text = path.read_text(errors="replace")
        texts.append(text)
        own_decls.update(DECL_RE.findall(text))
    for text in texts:
        for module in IMPORT_RE.findall(text):
            module = shims.get(module, module)
            if module_exists(module):
                modules.add(module)
        for name in NAME_RE.findall(text):
            name = name.rstrip("'.")
            parts = name.split(".")
            last = parts[-1]
            if last[:1].islower() is False and last[:1].isupper() is False:
                continue
            if last in own_decls and last not in short_names:
                continue
            if last not in short_names or last == "mk":
                continue
            if any(part in own_roots for part in parts[:1]):
                continue
            names.add(name)
    return sorted(modules), sorted(names)


def render(surface: dict) -> str:
    modules = sorted({m for consumer in surface["consumers"].values() for m in consumer["modules"]})
    lines = [HEADER]
    lines += [f"import {m}\n" for m in modules]
    lines.append(DOCSTRING)
    for consumer, data in sorted(surface["consumers"].items()):
        lines.append(f"\n/-! ## {consumer} -/\n\n")
        for name in data["declarations"]:
            line = f"noncomputable example := @{name}"
            # Keep the generated file inside the repository's 100-column style limit.
            lines.append(line + "\n" if len(line) <= 100 else f"noncomputable example :=\n  @{name}\n")
    return "".join(lines)


def load_surface() -> dict:
    return json.loads(SURFACE_JSON.read_text())


def cmd_check() -> int:
    expected = render(load_surface())
    actual = CANARY.read_text() if CANARY.exists() else ""
    if expected != actual:
        print(f"❌ {CANARY.relative_to(REPO_ROOT)} is out of date with "
              f"{SURFACE_JSON.relative_to(REPO_ROOT)}; run "
              "`python3 scripts/downstream-surface.py check --fix`.", file=sys.stderr)
        return 1
    print("✓ Downstream surface canary is up to date.")
    return 0


def cmd_fix() -> int:
    CANARY.parent.mkdir(parents=True, exist_ok=True)
    CANARY.write_text(render(load_surface()))
    print(f"✓ Wrote {CANARY.relative_to(REPO_ROOT)}")
    return 0


def cmd_refresh(args: argparse.Namespace) -> int:
    surface = load_surface() if SURFACE_JSON.exists() else {"consumers": {}}
    consumers = {"VCVio": (args.vcvio, {"VCVio", "OracleComp", "OracleSpec", "QueryImpl"}),
                 "ArkLib": (args.arklib, {"ArkLib"})}
    for consumer, (path, own_roots) in consumers.items():
        if path is None:
            continue
        modules, names = scan_consumer(Path(path), own_roots)
        surface["consumers"][consumer] = {"modules": modules, "declarations": names}
        print(f"{consumer}: {len(modules)} modules, {len(names)} declarations")
    SURFACE_JSON.write_text(json.dumps(surface, indent=2, ensure_ascii=False) + "\n")
    return cmd_fix()


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    sub = parser.add_subparsers(dest="command", required=True)
    check = sub.add_parser("check", help="regenerate from JSON and compare")
    check.add_argument("--fix", action="store_true", help="rewrite the canary instead of diffing")
    refresh = sub.add_parser("refresh", help="rescan consumer checkouts and rewrite the JSON")
    refresh.add_argument("--vcvio", help="path to a VCVio checkout")
    refresh.add_argument("--arklib", help="path to an ArkLib checkout")
    args = parser.parse_args()
    if args.command == "check":
        return cmd_fix() if args.fix else cmd_check()
    return cmd_refresh(args)


if __name__ == "__main__":
    sys.exit(main())
