/-
Copyright (c) 2026 PolyFun Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Quang Dao
-/
module

public import PolyFun.PFunctor.Dynamical.DynComputation.Bounded

/-!
# Qualitative termination of returning dynamical computations

This module separates branchwise well-founded termination from termination
within a uniform natural-number query budget. Accessibility of the visible
query-child relation is strong enough to extract a well-founded `FreeM` program,
including for infinitely branching programs whose branch depths have no
uniform bound.
-/

@[expose] public section

universe u v uA uB uα uβ uγ

namespace PFunctor

namespace DynSystem.DynComputation

variable {p : PFunctor.{uA, uB}} {α : Type uα} {β : Type uβ}
  {γ : Type uγ}

/-! ## Query accessibility -/

/-- The strict child relation generated by one visible query. Terminal states
have no children. -/
def QueryChild (M : DynComputation.{u} p α β) (child parent : M.State) : Prop :=
  ∃ position : p.A, ∃ next : p.B position → M.State,
    ∃ direction : p.B position,
    M.view parent = Sum.inr (⟨position, next⟩ : p.Obj M.State) ∧
      child = next direction

/-- Every branch from `state` contains only finitely many visible queries.
Unlike `ResolvesIn`, different branches need not share a natural-number
bound. -/
def TerminatesFrom (M : DynComputation.{u} p α β) (state : M.State) : Prop :=
  Acc M.QueryChild state

theorem queryChild_of_view (M : DynComputation.{u} p α β)
    (state : M.State) (position : p.A) (next : p.B position → M.State)
    (direction : p.B position)
    (hview : M.view state =
      Sum.inr (⟨position, next⟩ : p.Obj M.State)) :
    M.QueryChild (next direction) state :=
  ⟨position, next, direction, hview, rfl⟩

@[simp] theorem terminatesFrom_return (M : DynComputation.{u} p α β)
    (state : M.State) (value : β) (hview : M.view state = Sum.inl value) :
    M.TerminatesFrom state := by
  constructor
  rintro child ⟨position, next, direction, hquery, rfl⟩
  rw [hview] at hquery
  cases hquery

theorem terminatesFrom_query_iff (M : DynComputation.{u} p α β)
    (state : M.State) (position : p.A) (next : p.B position → M.State)
    (hview : M.view state = Sum.inr ⟨position, next⟩) :
    M.TerminatesFrom state ↔ ∀ direction, M.TerminatesFrom (next direction) := by
  constructor
  · intro h direction
    exact h.inv ⟨position, next, direction, hview, rfl⟩
  · intro h
    constructor
    rintro child ⟨position', next', direction, hquery, rfl⟩
    have hquery' :
        (⟨position', next'⟩ : p.Obj M.State) = ⟨position, next⟩ := by
      exact Sum.inr_injective (hquery.symm.trans hview)
    cases hquery'
    exact h direction

/-! ## Well-founded-program extraction -/

/-- Extract the well-founded free program represented below an accessible
hidden state. Lean's computable accessibility recursor `Acc.recC` may
eliminate into `Type`, so this construction does not choose branch witnesses. -/
def toFreeMFrom (M : DynComputation.{u} p α β) :
    (_state : M.State) → M.TerminatesFrom _state → FreeM p β :=
  fun _ termination =>
    Acc.recC (motive := fun _ _ => FreeM p β)
      (fun current _ recurse =>
        match hview : M.view current with
        | Sum.inl value => FreeM.pure value
        | Sum.inr ⟨position, next⟩ =>
            FreeM.liftBind position fun direction =>
              recurse (next direction)
                ⟨position, next, direction,
                  (show M.view current =
                    Sum.inr (⟨position, next⟩ : p.Obj M.State) from hview),
                  rfl⟩)
      termination

/-- Extract the well-founded program family represented from every
input-selected initial state. -/
def toFreeM (M : DynComputation.{u} p α β)
    (termination : ∀ input, M.TerminatesFrom (M.init input))
    (input : α) : FreeM p β :=
  M.toFreeMFrom (M.init input) (termination input)

@[simp] theorem toFreeMFrom_return (M : DynComputation.{u} p α β)
    (state : M.State) (termination : M.TerminatesFrom state)
    (value : β) (hview : M.view state = Sum.inl value) :
    M.toFreeMFrom state termination = FreeM.pure value := by
  unfold toFreeMFrom
  rw [← Acc.rec_eq_recC]
  cases termination
  dsimp
  split
  · rename_i value' hcase
    cases Sum.inl.inj (hcase.symm.trans hview)
    rfl
  · rename_i position' next' hcase
    rw [hview] at hcase
    contradiction

theorem toFreeMFrom_query (M : DynComputation.{u} p α β)
    (state : M.State) (termination : M.TerminatesFrom state)
    (position : p.A) (next : p.B position → M.State)
    (hview : M.view state =
      Sum.inr (⟨position, next⟩ : p.Obj M.State)) :
    M.toFreeMFrom state termination =
      FreeM.liftBind position fun direction =>
        M.toFreeMFrom (next direction)
          (termination.inv
            (M.queryChild_of_view state position next direction hview)) := by
  unfold toFreeMFrom
  rw [← Acc.rec_eq_recC]
  cases termination
  dsimp
  split
  · rename_i value hcase
    rw [hview] at hcase
    contradiction
  · rename_i position' next' hcase
    have hsigma :
        (⟨position', next'⟩ : p.Obj M.State) = ⟨position, next⟩ :=
      Sum.inr.inj (hcase.symm.trans hview)
    have hp := (Sigma.mk.inj hsigma).1
    subst position
    have hn : next' = next := eq_of_heq (Sigma.mk.inj hsigma).2
    subst next
    apply congrArg (FreeM.liftBind position')
    funext direction
    congr

/-- Extracted programs do not depend on the particular accessibility proof. -/
theorem toFreeMFrom_proof_irrel (M : DynComputation.{u} p α β)
    (state : M.State) (h₁ h₂ : M.TerminatesFrom state) :
    M.toFreeMFrom state h₁ = M.toFreeMFrom state h₂ := by
  congr

/-- Extracted program families do not depend on the pointwise accessibility
proof. -/
theorem toFreeM_proof_irrel (M : DynComputation.{u} p α β)
    (h₁ h₂ : ∀ input, M.TerminatesFrom (M.init input)) :
    M.toFreeM h₁ = M.toFreeM h₂ := by
  funext input
  exact M.toFreeMFrom_proof_irrel (M.init input) (h₁ input) (h₂ input)

/-! ## Exact well-founded semantics -/

/-- Extraction preserves the computation's exact state behavior. The proof
uses the established M-type equality principle but performs no branchwise
witness choice. -/
theorem behavior_eq_toResumption_toFreeMFrom
    (M : DynComputation.{u} p α β) (state : M.State)
    (termination : M.TerminatesFrom state) :
    M.toDynSystem.behavior state =
      FreeM.toResumption (M.toFreeMFrom state termination) := by
  induction termination with
  | intro state below ih =>
      cases hview : M.view state with
      | inl value =>
          apply Resumption.eq_of_dest_eq
          rw [M.dest_behavior_view, hview,
            M.toFreeMFrom_return state _ value hview]
          rfl
      | inr query =>
          rcases query with ⟨position, next⟩
          apply Resumption.eq_of_dest_eq
          rw [M.dest_behavior_view, hview,
            M.toFreeMFrom_query state _ position next hview]
          simp only [Sum.map_inr, PFunctor.map_eq,
            FreeM.dest_toResumption_liftBind]
          apply congrArg Sum.inr
          apply Sigma.ext
          · rfl
          · apply heq_of_eq
            funext direction
            exact ih (next direction)
              (M.queryChild_of_view state position next direction hview)

/-- Input-level specialization of exact extraction. -/
theorem denote_eq_toResumption_toFreeM (M : DynComputation.{u} p α β)
    (termination : ∀ input, M.TerminatesFrom (M.init input)) (input : α) :
    M.denote input = FreeM.toResumption (M.toFreeM termination input) :=
  M.behavior_eq_toResumption_toFreeMFrom (M.init input) (termination input)

/-- A uniform query bound implies qualitative well-founded termination. -/
theorem ResolvesIn.terminatesFrom {M : DynComputation.{u} p α β}
    {k : ℕ} {state : M.State} (h : M.ResolvesIn k state) :
    M.TerminatesFrom state := by
  induction k generalizing state with
  | zero =>
      obtain ⟨value, hview⟩ := (M.resolvesIn_zero state).mp h
      exact M.terminatesFrom_return state value hview
  | succ k ih =>
      cases hview : M.view state with
      | inl value => exact M.terminatesFrom_return state value hview
      | inr query =>
          rcases query with ⟨position, next⟩
          apply (M.terminatesFrom_query_iff state position next hview).mpr
          intro direction
          exact ih ((M.resolvesIn_query_succ_iff k state position next hview).mp h direction)

/-- A state with the same one-step view as a terminating state terminates.
This is useful when a stateful construction changes only the hidden owner of
an otherwise identical residual query. -/
theorem TerminatesFrom.of_view_eq {M : DynComputation.{u} p α β}
    {source target : M.State} (h : M.TerminatesFrom target)
    (hview : M.view source = M.view target) : M.TerminatesFrom source := by
  cases htarget : M.view target with
  | inl value =>
      exact M.terminatesFrom_return source value (hview.trans htarget)
  | inr query =>
      rcases query with ⟨position, next⟩
      apply (M.terminatesFrom_query_iff source position next (hview.trans htarget)).mpr
      exact (M.terminatesFrom_query_iff target position next htarget).mp h

/-- A well-founded `FreeM` presentation proves accessibility of the state that
realizes it. This direction is structural in the supplied `FreeM`; it does
not assume or manufacture a uniform natural-number depth bound. -/
theorem terminatesFrom_of_behavior_eq_toResumption
    (M : DynComputation.{u} p α β) (program : FreeM p β)
    (state : M.State)
    (hsem : M.toDynSystem.behavior state = FreeM.toResumption program) :
    M.TerminatesFrom state := by
  induction program using FreeM.induction generalizing state with
  | pure value =>
      cases hview : M.view state with
      | inl result => exact M.terminatesFrom_return state result hview
      | inr query =>
          have hdest := congrArg Resumption.dest hsem
          have hleft := M.dest_behavior_view state
          rw [hview] at hleft
          have himpossible : Sum.inr (p.map M.toDynSystem.behavior query) =
              Sum.inl value :=
            hleft.symm.trans (hdest.trans (FreeM.dest_toResumption_pure value))
          cases himpossible
  | lift_bind position children ih =>
      cases hview : M.view state with
      | inl result =>
          have hdest := congrArg Resumption.dest hsem
          have hleft := M.dest_behavior_view state
          rw [hview] at hleft
          have himpossible : Sum.inl result = Sum.inr
              (⟨position,
                fun direction => FreeM.toResumption (children direction)⟩ :
                  p.Obj (Resumption p β)) :=
            hleft.symm.trans
              (hdest.trans (FreeM.dest_toResumption_liftBind position children))
          cases himpossible
      | inr query =>
          rcases query with ⟨source, next⟩
          have hdest := congrArg Resumption.dest hsem
          have hleft := M.dest_behavior_view state
          rw [hview] at hleft
          have hdest' := hleft.symm.trans
            (hdest.trans (FreeM.dest_toResumption_liftBind position children))
          simp only [Sum.map_inr, PFunctor.map_eq] at hdest'
          have hsigma := Sum.inr.inj hdest'
          have hposition : source = position := (Sigma.mk.inj hsigma).1
          subst position
          have hnext :
              (fun direction => M.toDynSystem.behavior (next direction)) =
                fun direction => FreeM.toResumption (children direction) :=
            eq_of_heq (Sigma.mk.inj hsigma).2
          apply (M.terminatesFrom_query_iff state source next hview).mpr
          intro direction
          exact ih direction (next direction) (congrFun hnext direction)

/-- Accessibility is exactly existence of a well-founded free-program
presentation of the state's coinductive behavior. -/
theorem terminatesFrom_iff_exists_behavior_eq_toResumption
    (M : DynComputation.{u} p α β) (state : M.State) :
    M.TerminatesFrom state ↔
      ∃ program : FreeM p β,
        M.toDynSystem.behavior state = FreeM.toResumption program := by
  constructor
  · intro h
    exact ⟨M.toFreeMFrom state h,
      M.behavior_eq_toResumption_toFreeMFrom state h⟩
  · rintro ⟨program, hsem⟩
    exact M.terminatesFrom_of_behavior_eq_toResumption program state hsem

/-- Exact quantitative characterization of an extracted qualitative
program. A qualitative proof alone need not supply any such `k`. -/
theorem resolvesIn_iff_isTotalRollBound_toFreeMFrom
    (M : DynComputation.{u} p α β) (k : ℕ) (state : M.State)
    (termination : M.TerminatesFrom state) :
    M.ResolvesIn k state ↔
      (M.toFreeMFrom state termination).IsTotalRollBound k :=
  M.resolvesIn_iff_isTotalRollBound_of_behavior_eq k state
    (M.toFreeMFrom state termination)
    (M.behavior_eq_toResumption_toFreeMFrom state termination)

/-- The extracted initial program family is implemented exactly. -/
theorem implements_toFreeM (M : DynComputation.{u} p α β)
    (termination : ∀ input, M.TerminatesFrom (M.init input)) :
    M.Implements (M.toFreeM termination) :=
  M.denote_eq_toResumption_toFreeM termination

/-- A computation terminates from every entry state exactly when it
qualitatively implements some well-founded free-program family. -/
theorem terminatesFrom_init_iff_exists_implements
    (M : DynComputation.{u} p α β) :
    (∀ input, M.TerminatesFrom (M.init input)) ↔
      ∃ program : α → FreeM p β, M.Implements program := by
  constructor
  · intro h
    exact ⟨M.toFreeM h, M.implements_toFreeM h⟩
  · rintro ⟨program, h⟩ input
    exact M.terminatesFrom_of_behavior_eq_toResumption
      (program input) (M.init input) (h input)

/-! ## Qualitative sequential composition -/

/-- A terminating second-phase state remains terminating when embedded in
the right phase of sequential composition. -/
theorem TerminatesFrom.seqComp_inr {M₁ : DynComputation.{u} p α β}
    {M₂ : DynComputation.{v} p β γ} {state₂ : M₂.State}
    (h₂ : M₂.TerminatesFrom state₂) :
    (M₁.seqComp M₂).TerminatesFrom (Sum.inr state₂) := by
  induction h₂ with
  | intro state below ih =>
      cases hview : M₂.view state with
      | inl value =>
          apply (M₁.seqComp M₂).terminatesFrom_return (Sum.inr state) value
          rw [seqComp_view_inr, hview]
          rfl
      | inr query =>
          rcases query with ⟨position, next⟩
          have hcomposite :
              (M₁.seqComp M₂).view (Sum.inr state) =
                Sum.inr ⟨position, fun direction => Sum.inr (next direction)⟩ := by
            rw [seqComp_view_inr, hview]
            rfl
          apply ((M₁.seqComp M₂).terminatesFrom_query_iff
            (Sum.inr state) position (fun direction => Sum.inr (next direction))
            hcomposite).mpr
          intro direction
          exact ih (next direction)
            (M₂.queryChild_of_view state position next direction hview)

/-- Sequential composition terminates in phase one when phase one terminates
and the second computation terminates from every possible handoff value. -/
theorem TerminatesFrom.seqComp_inl {M₁ : DynComputation.{u} p α β}
    {M₂ : DynComputation.{v} p β γ} {state₁ : M₁.State}
    (h₁ : M₁.TerminatesFrom state₁)
    (h₂ : ∀ value, M₂.TerminatesFrom (M₂.init value)) :
    (M₁.seqComp M₂).TerminatesFrom (Sum.inl state₁) := by
  induction h₁ with
  | intro state below ih =>
      cases hview : M₁.view state with
      | inl value =>
          apply (h₂ value).seqComp_inr.of_view_eq
          simp only [seqComp_view_inl, hview, seqComp_view_inr]
          rfl
      | inr query =>
          rcases query with ⟨position, next⟩
          have hcomposite :
              (M₁.seqComp M₂).view (Sum.inl state) =
                Sum.inr ⟨position, fun direction => Sum.inl (next direction)⟩ := by
            rw [seqComp_view_inl, hview]
            rfl
          apply ((M₁.seqComp M₂).terminatesFrom_query_iff
            (Sum.inl state) position (fun direction => Sum.inl (next direction))
            hcomposite).mpr
          intro direction
          exact ih (next direction)
            (M₁.queryChild_of_view state position next direction hview)

/-- Input-level qualitative termination composes through sequential
handoff. -/
theorem TerminatesFrom.seqComp_init {M₁ : DynComputation.{u} p α β}
    {M₂ : DynComputation.{v} p β γ}
    (h₁ : ∀ input, M₁.TerminatesFrom (M₁.init input))
    (h₂ : ∀ value, M₂.TerminatesFrom (M₂.init value))
    (input : α) :
    (M₁.seqComp M₂).TerminatesFrom ((M₁.seqComp M₂).init input) := by
  change (M₁.seqComp M₂).TerminatesFrom (Sum.inl (M₁.init input))
  exact (h₁ input).seqComp_inl h₂

/-- Extraction from a right-phase state is exactly extraction from the
second computation. -/
theorem toFreeMFrom_seqComp_inr
    (M₁ : DynComputation.{u} p α β) (M₂ : DynComputation.{v} p β γ)
    (state₂ : M₂.State) (h₂ : M₂.TerminatesFrom state₂) :
    (M₁.seqComp M₂).toFreeMFrom (Sum.inr state₂) h₂.seqComp_inr =
      M₂.toFreeMFrom state₂ h₂ := by
  apply FreeM.toResumption_injective
  calc
    FreeM.toResumption
        ((M₁.seqComp M₂).toFreeMFrom (Sum.inr state₂) h₂.seqComp_inr) =
        (M₁.seqComp M₂).toDynSystem.behavior (Sum.inr state₂) :=
      ((M₁.seqComp M₂).behavior_eq_toResumption_toFreeMFrom
        (Sum.inr state₂) h₂.seqComp_inr).symm
    _ = M₂.toDynSystem.behavior state₂ := behavior_seqComp_inr M₁ M₂ state₂
    _ = FreeM.toResumption (M₂.toFreeMFrom state₂ h₂) :=
      M₂.behavior_eq_toResumption_toFreeMFrom state₂ h₂

/-- Extraction from a terminating phase-one state is literal free-monad
bind of the two extracted phases. -/
theorem toFreeMFrom_seqComp_inl
    (M₁ : DynComputation.{u} p α β) (M₂ : DynComputation.{v} p β γ)
    (state₁ : M₁.State) (h₁ : M₁.TerminatesFrom state₁)
    (h₂ : ∀ value, M₂.TerminatesFrom (M₂.init value)) :
    (M₁.seqComp M₂).toFreeMFrom (Sum.inl state₁) (h₁.seqComp_inl h₂) =
      FreeM.bind (M₁.toFreeMFrom state₁ h₁)
        (fun value => M₂.toFreeMFrom (M₂.init value) (h₂ value)) := by
  apply FreeM.toResumption_injective
  rw [FreeM.toResumption_bind]
  calc
    FreeM.toResumption
        ((M₁.seqComp M₂).toFreeMFrom (Sum.inl state₁)
          (h₁.seqComp_inl h₂)) =
        (M₁.seqComp M₂).toDynSystem.behavior (Sum.inl state₁) :=
      ((M₁.seqComp M₂).behavior_eq_toResumption_toFreeMFrom
        (Sum.inl state₁) (h₁.seqComp_inl h₂)).symm
    _ = Resumption.bind (M₁.toDynSystem.behavior state₁) M₂.denote :=
      behavior_seqComp_inl M₁ M₂ state₁
    _ = Resumption.bind
        (FreeM.toResumption (M₁.toFreeMFrom state₁ h₁))
        (fun value =>
          FreeM.toResumption
            (M₂.toFreeMFrom (M₂.init value) (h₂ value))) := by
      apply congrArg₂ Resumption.bind
      · exact M₁.behavior_eq_toResumption_toFreeMFrom state₁ h₁
      · funext value
        exact M₂.behavior_eq_toResumption_toFreeMFrom
          (M₂.init value) (h₂ value)

/-- Program-family extraction commutes exactly with sequential composition. -/
theorem toFreeM_seqComp
    (M₁ : DynComputation.{u} p α β) (M₂ : DynComputation.{v} p β γ)
    (h₁ : ∀ input, M₁.TerminatesFrom (M₁.init input))
    (h₂ : ∀ value, M₂.TerminatesFrom (M₂.init value)) :
    (M₁.seqComp M₂).toFreeM (fun input => (h₁ input).seqComp_inl h₂) =
      fun input => FreeM.bind (M₁.toFreeM h₁ input) (M₂.toFreeM h₂) := by
  funext input
  exact toFreeMFrom_seqComp_inl M₁ M₂ (M₁.init input) (h₁ input) h₂

end DynSystem.DynComputation

end PFunctor
