/-
Copyright (c) 2026 PolyFun Contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Quang Dao
-/
import PolyFun.Interaction.Basic.Append

/-!
# Well-founded stopping trees (`Spec.Telescope`)

`Telescope round step` is the indexed W-type generated by either stopping at
the current state or extending by one protocol round and branching over all of
its transcripts. Equivalently, it is the initial algebra of the indexed
polynomial

```
H X s = PUnit ⊕ ((tr : Transcript (round s)) → X (step s tr)).
```

Given
* a state space `St : Type v`,
* a round assignment `round : St → Spec.{u}`,
* a state transition `step : (s : St) → Transcript (round s) → St`,

an inhabitant of `Telescope round step s₀` is a well-founded stopping tree.
It may be infinitely branching, and its branches need not have a common finite
height. Moreover, `.done s` is available at every state, so mere inhabitation
does **not** prove termination of the underlying state machine. A termination
certificate would instead restrict where stopping is allowed (for example by
a halting predicate or a well-founded ranking).

## Universal property

`PFunctor.FreeM.StoppingTree.Algebra`, `fold`, and `eq_fold` formalize the
initial-algebra universal property. `toSpec` is the fold into the algebra
`(fun _ => Spec, .done, fun s cont => (round s).append cont)`.

## References

* Hancock–Setzer (2000), recursion over interaction interfaces.
* Spivak–Niu (2024), polynomial functors as the algebra of interaction.
-/

universe u v

namespace Interaction
namespace Spec

/-- Initial-algebra presentation of a state-machine telescope of `Spec`s.

At each state `s : St`, an inhabitant either stops (`.done s`) or extends
by running the round `round s : Spec` and recursing into
`Telescope round step (step s tr)` for every transcript `tr`. The inductive is
well-founded, but may be infinitely branching and is not itself a termination
certificate because stopping is permitted at every state.

The `(round, step)` data is exactly a coalgebra of the undecorated step
polynomial `Spec.stepPoly` — a `PFunctor.DynSystem St Spec.stepPoly`
unpacked on its states. -/
abbrev Telescope {St : Type v}
    (round : St → Spec.{u})
    (step : (s : St) → Transcript (round s) → St) : St → Type (max u v) :=
  PFunctor.FreeM.StoppingTree (fun s => Transcript (round s)) step

namespace Telescope

variable {St : Type v} {round : St → Spec.{u}}
    {step : (s : St) → Transcript (round s) → St}

/-- Constructor wrapper for terminating a `Spec.Telescope`. -/
abbrev done (s : St) : Telescope round step s :=
  PFunctor.FreeM.StoppingTree.done s

/-- Constructor wrapper for extending a `Spec.Telescope` by one round. -/
abbrev extend (s : St)
    (cont : (tr : Transcript (round s)) → Telescope round step (step s tr)) :
    Telescope round step s :=
  PFunctor.FreeM.StoppingTree.extend s cont

/-- The `Spec`-valued algebra interpreting a stopping leaf as the substitution
unit and a transition layer as substitution multiplication. -/
def toSpecAlgebra :
    PFunctor.FreeM.StoppingTree.Algebra
      (Obs := fun s => Transcript (round s)) (step := step) (fun _ => Spec) where
  done _ := Spec.done
  extend s cont := Spec.substMonoid.mult.toFunA ⟨round s, cont⟩

/-- Fold a `Telescope` into a concrete `Spec` using the canonical substitution
monoid: `done` is its unit and `extend` is its multiplication/append. -/
def toSpec : {s : St} → Telescope round step s → Spec :=
  PFunctor.FreeM.StoppingTree.fold toSpecAlgebra

@[simp, grind =]
theorem toSpec_done (s : St) :
    (Telescope.done (round := round) (step := step) s).toSpec = .done := rfl

@[simp, grind =]
theorem toSpec_extend (s : St)
    (cont : (tr : Transcript (round s)) → Telescope round step (step s tr)) :
    (Telescope.extend s cont).toSpec =
      (round s).append (fun tr => (cont tr).toSpec) := rfl

/-- Universal property of `toSpec`: any interpretation that sends stopping
leaves to `Spec.done` and transition layers to substitution multiplication
agrees pointwise with `toSpec`. -/
theorem eq_toSpec
    (f : {s : St} → Telescope round step s → Spec)
    (hDone : (s : St) → f (Telescope.done s) = Spec.done)
    (hExtend : (s : St) →
      (cont : (tr : Transcript (round s)) → Telescope round step (step s tr)) →
      f (Telescope.extend s cont) =
        Spec.substMonoid.mult.toFunA ⟨round s, fun tr => f (cont tr)⟩) :
    {s : St} → (tree : Telescope round step s) → f tree = tree.toSpec :=
  PFunctor.FreeM.StoppingTree.eq_fold toSpecAlgebra f hDone hExtend

end Telescope
end Spec
end Interaction
