name: API Docs

on:
  push:
    branches: [main]

concurrency:
  group: github-pages
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  docs:
    name: Build and publish API docs
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: https://verified-zkevm.github.io/PolyFun/docs/
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0

      - name: Build project
        uses: leanprover/lean-action@38fbc41a8c28c4cbaec22d7f7de508ec2e7c0dd9 # v1.5.0
        with:
          build-args: --log-level=warning

      - name: Build and publish documentation
        id: docs
        uses: leanprover-community/docgen-action@10db47458f91456d87804787d3dfcd914b9a19e3 # main, 2026-08-08
        with:
          build-page: false
